const Base = require('../../BaseClass/base')
const ecoPage = require('../../Pages/Androidbrowser/ecoInspectionPage')
describe('ECOInspection', () => {
    beforeEach(async () => {
        await driver.closeApp()
        await driver.launchApp()
    });
 it('TC_01 Verify the Functionaliy of Buyer on ECO', async () => {
        await browser.url('/user/login')   
        console.log("Traversing towards ECO Inspection")   
        await  ecoPage.traverseToECO()
        await (await ecoPage.Buyer).isDisplayed()
        console.log("Buyer is availbale on ECO page")
        await (await ecoPage.Seller).isDisplayed()
        console.log("Seller is availbale on ECO page")
        await (await ecoPage.Technician).isDisplayed()
        console.log("Technician is availbale on ECO page")
        await(await ecoPage.Buyer).click()
        console.log("Clicked on Buyer")
        expect(await ecoPage.Check_Repair_Estimate).toBeDisplayed()
        console.log("Check Repair Estimate is displayed")
        await(await ecoPage.Check_Repair_Estimate).click()
        console.log("Clicked on Check Repair Estimate")
        await(await ecoPage.checkRepairEstiHeading).waitForDisplayed({timeout:15000})
        expect(await ecoPage.checkRepairEstiHeading).toBeDisplayed()
        console.log("Heading is displayed as : "+await(await ecoPage.checkRepairEstiHeading).getText())
        await base.scrollToExactText("Select Make")
        expect(await ecoPage.make1).toBeDisplayed()
        console.log("Select Make is Displayed")
        await(await ecoPage.make1).click()
        console.log("Clicked on Make")
        await(await ecoPage.MakeName).click()
        console.log("Selected the Make Name")
        await(await ecoPage.model1).click()
        console.log("Clicked on Model")
        await(await ecoPage.ModelName).click()
        console.log("Selected the Model Name")
        await(await ecoPage.Trim1).click()
        console.log("Clicked on the Trim Field")
        await(await ecoPage.TrimTo).click()
        console.log("Selected trim to option")
        await(await ecoPage.location).click()
        console.log("Clicked on the Location")
        await(await ecoPage.myLocation).click()
        console.log("Clicked on the Location")
        await(await ecoPage.MyLocation).setValue("Delhi")
        console.log("Set the location")
        await(await ecoPage.delhi).click()
        await(await ecoPage.Next).click()
        expect(await ecoPage.repairServiceHeading).isDisplayed()
        console.log("Heading is displayed as : "+await(await ecoPage.repairServiceHeading ).getText())
        await(await ecoPage.airFilter).click()
        await Base.swipeUp()
        await(await ecoPage.getEstimate).click()
        expect(await ecoPage.Estimated_RepairCost).isDisplayed()
        console.log(await(await ecoPage.Estimated_RepairCost).getText())
    }); 
    it('TC_04 Verify Features on ECO for Four Wheelers', async () => {
        await browser.url('/user/login')
        await  ecoPage.traverseToECO()
        await (await ecoPage.Seller).isDisplayed()
        console.log("Seller is availbale on ECO page")
        await (await ecoPage.Seller).click()
        expect(ecoPage.RegiAsVendor).toBeDisplayed()
        console.log("Register As a Vendor is Displayed")
        await (await ecoPage.RegiAsVendor).click()
        console.log("Clicked on Resister as Vendor")
        await(await ecoPage.hamburgurOnEco).click()
        console.log("Traversing to the Features , SIgn Up, Services")
        await (await ecoPage.features).click()
        console.log("Clicked on Features")
        expect(await ecoPage.features_FourWheelers).toBeDisplayed()
        console.log("ECO inspection Page is Displayed for Four wheelers")
        expect(await ecoPage.chechPoint_FourWheeler).toBeDisplayed()
        console.log("checkpoint for four wheelers are displayed")
        expect(await ecoPage.assessment).toBeDisplayed()
        console.log(await (ecoPage.assessment).getText())
        console.log("Inspection Checkpoints for Four Wheeler Displayed");
    });
    it('TC_05 Verify Features on ECO for Two Wheelers', async () => {
       await browser.url('/user/login')
        expect(await ecoPage.featurs_TwoWheelers).toBeDisplayed()
        await(await ecoPage.featurs_TwoWheelers).click()
        console.log("Clicked on Two Wheelers");
        expect(await ecoPage.chechPoint_TwoWheeler).toBeDisplayed()
        console.log(await (await ecoPage.chechPoint_TwoWheeler).getText())
        console.log("Check Points for Two Wheeler displayed")
        expect(await ecoPage.tires_Wheels).toBeDisplayed()
        console.log(await (await ecoPage.tires_Wheels).getText())
    });
});