const Base = require('../../BaseClass/base')
const ecoPage = require('../../Pages/Androidbrowser/ecoInspectionPage')
describe('ECOInspection', () => {
    beforeEach(async () => {
        await driver.closeApp()
        await driver.launchApp()
    });
 it('TC_01 Verify the Functionaliy of Buyer on ECO', async () => {
        await browser.url('/eco')   
       // console.log("Traversing towards ECO Inspection")   
        //await  ecoPage.traverseToECO()
        await (await ecoPage.Buyer).isDisplayed()
        console.log("Buyer is availbale on ECO page")
        await (await ecoPage.Seller).isDisplayed()
        console.log("Seller is availbale on ECO page")
        await (await ecoPage.Technician).isDisplayed()
        console.log("Technician is availbale on ECO page")
        await(await ecoPage.Buyer).click()
        console.log("Clicked on Buyer")
        expect(await ecoPage.Check_Repair_Estimate).toBeDisplayed()
        console.log("Check Repair Estimate is displayed")
        await(await ecoPage.Check_Repair_Estimate).click()
        console.log("Clicked on Check Repair Estimate")
        await(await ecoPage.checkRepairEstiHeading).waitForDisplayed({timeout:15000})
        expect(await ecoPage.checkRepairEstiHeading).toBeDisplayed()
        console.log("Heading is displayed as : "+await(await ecoPage.checkRepairEstiHeading).getText())
        //await Base.scrollToExactText("Select Make")
        expect(await ecoPage.make1).toBeDisplayed()
        console.log("Select Make is Displayed")
        await(await ecoPage.make1).click()
        console.log("Clicked on Make")
        await(await ecoPage.MakeName).click()
        console.log("Selected the Make Name")
        await(await ecoPage.model1).click()
        console.log("Clicked on Model")
        await(await ecoPage.ModelName).click()
        console.log("Selected the Model Name")
        await(await ecoPage.Trim1).click()
        console.log("Clicked on the Trim Field")
        await(await ecoPage.TrimTo).click()
        console.log("Selected trim to option")
        await(await ecoPage.location).click()
        console.log("Clicked on the Location")
        await(await ecoPage.myLocation).click()
        console.log("Clicked on the Location")
        await(await ecoPage.MyLocation).setValue("Delhi")
        console.log("Set the location")
        await(await ecoPage.delhi).click()
        await(await ecoPage.Next).click()
        expect(await ecoPage.repairServiceHeading).toBeDisplayed()
        console.log("Heading is displayed as : "+await(await ecoPage.repairServiceHeading ).getText())
        await(await ecoPage.airFilter).click()
        //await Base.swipeUp()
        await(await ecoPage.getEstimate).click()
        expect(await ecoPage.Estimated_RepairCost).isDisplayed()
        console.log(await(await ecoPage.Estimated_RepairCost).getText())
    });
     it('TC_02 Verify the Functionality of Seller on ECO with Register as Vendor', async () => {
        await browser.url('/ecoinspection.in')   
        //await  ecoPage.traverseToECO()
        //await (await ecoPage.Seller).click()
        //expect(ecoPage.RegiAsVendor).toBeDisplayed()
        //console.log("Register As a Vendor is Displayed")
        //await (await ecoPage.RegiAsVendor).click()
        //console.log("Clicked on Resister as Vendor")
        expect(ecoPage.createUrAccount).toBeDisplayed()
        console.log("Create Your Account heading is displayed")
        expect(ecoPage.mandatoryNote).toBeDisplayed()
        console.log("All fields are mandatory note is displayed")
        expect(ecoPage.fName).toBeDisplayed()
        console.log("Full Name fields shown")
        expect(ecoPage.emailId).toBeDisplayed()
        console.log("Email Id  fields shown")
        expect(ecoPage.PhoneNo).toBeDisplayed()
        console.log("Phone Number fields shown")
        expect(ecoPage.pinCode).toBeDisplayed()
        console.log(" Pin Code fields shown")
        Base.swipeUp()
        expect(ecoPage.cityName).toBeDisplayed()
        console.log("City Name fields shown")
        expect(ecoPage.state).toBeDisplayed()
        console.log("State fields shown")
        expect(ecoPage.Building).toBeDisplayed()
        console.log("Building/Area/Locality fields shown")
        expect(ecoPage.contactName).toBeDisplayed()
        console.log("Contact Name Filed is Shown")
        expect(ecoPage.contactEmail).toBeDisplayed()
        console.log("Contact Email Filed is Shown")
        Base.swipeUp()
        expect(ecoPage.contactPhone).toBeDisplayed()
        console.log("Contact Phone Filed is Shown")
        expect(ecoPage.submitBtn).toBeDisplayed()
        console.log("Submit Button  Filed is Shown")
        expect(ecoPage.flowForVendor).toBeDisplayed()
        console.log("Inspection flow for Vendor is Shown")        
    })
    it('TC_03:Verify the Functionality of Seller on ECO with Register as Technician', async () => {
        await browser.url('/ecoinspection.in') 
       // await ecoPage.traverseToECO()
       //expect(await ecoPage.Technician).toBeDisplayed()
       //console.log("Seller Displayed")
        //await (await ecoPage.Technician).click()
        //console.log("Clicked on Seller Option")
       // expect(ecoPage.seller_RegiAsTechnician).toBeDisplayed()
        //console.log("Register As a Technician is Displayed")
        //await browser.pause(5000)
        //await (await ecoPage.seller_RegiAsTechnician).click()
        //console.log("Clicked on Resister as Technician")
        expect(ecoPage.createUrAccount).toBeDisplayed()
        console.log("Create Your Account heading is displayed")
        expect(ecoPage.mandatoryNote).toBeDisplayed()
        console.log("All fields are mandatory note is displayed")
        expect(ecoPage.firstName).toBeDisplayed()
        console.log("First Name field is Shown")
        expect(ecoPage.lastName).toBeDisplayed()
        console.log("Last Name field is Shown")
        expect(ecoPage.emailId).toBeDisplayed()
        console.log("Email ID field is Shown")
        expect(ecoPage.phoneNo).toBeDisplayed()
        console.log("Phone Number field is Shown")
        expect(ecoPage.pinCode).toBeDisplayed()
        console.log("Pin Code field is Shown")
        expect(ecoPage.cityName).toBeDisplayed()
        console.log("Enter City  Name field is Shown")
        expect(ecoPage.stateTechnician).toBeDisplayed()
        console.log("State field is Shown")
        expect(ecoPage.area).toBeDisplayed()
        console.log("Building/Area/Locality field is Shown")
        expect(ecoPage.passwordTechnician).toBeDisplayed()
        console.log("Password field is Shown")
        expect(ecoPage.submitBtn).toBeDisplayed()
        console.log(" Submit Button is Shown")
    })
    it('TC_04 Verify Features on ECO for Four Wheelers', async () => {
       await browser.url('https:/ecoinspection.in/signup?for=vendor') 
        //await  ecoPage.traverseToECO()
       /* await (await ecoPage.Seller).isDisplayed()
        console.log("Seller is availbale on ECO page")
        await (await ecoPage.Seller).click()
        expect(ecoPage.RegiAsVendor).toBeDisplayed()
        console.log("Register As a Vendor is Displayed")
        await (await ecoPage.RegiAsVendor).click()
        console.log("Clicked on Resister as Vendor")
        */
        await(await ecoPage.hamburgurOnEco).click()
        console.log("Traversing to the Features , SIgn Up, Services")
        await (await ecoPage.features).click()
        console.log("Clicked on Features")
        expect(await ecoPage.features_FourWheelers).toBeDisplayed()
        console.log("ECO inspection Page is Displayed for Four wheelers")
        expect(await ecoPage.chechPoint_FourWheeler).toBeDisplayed()
        console.log("checkpoint for four wheelers are displayed")
        expect(await ecoPage.assessment).toBeDisplayed()
        console.log(await (ecoPage.assessment).getText())
        console.log("Inspection Checkpoints for Four Wheeler Displayed");
    });
    it('TC_05 Verify Features on ECO for Two Wheelers', async () => {
     await browser.url('/ecoinspection.in') 
        expect(await ecoPage.featurs_TwoWheelers).toBeDisplayed()
        await(await ecoPage.featurs_TwoWheelers).click()
        console.log("Clicked on Two Wheelers");
        expect(await ecoPage.chechPoint_TwoWheeler).toBeDisplayed()
        console.log(await (await ecoPage.chechPoint_TwoWheeler).getText())
        console.log("Check Points for Two Wheeler displayed")
        expect(await ecoPage.tires_Wheels).toBeDisplayed()
        console.log(await (await ecoPage.tires_Wheels).getText())
    });
});