const Base = require('../../BaseClass/base')
const ecoPage = require('../../Pages/Androidbrowser/ecoInspectionPage')
describe('ECOInspection', () => {
    beforeEach(async () => {
        await driver.closeApp()
        await driver.launchApp()
    });
 /*it('TC_01 Verify the Functionaliy of Buyer on ECO', async () => {
        await browser.url('/user/login')   
        console.log("Traversing towards ECO Inspection")   
        await  ecoPage.traverseToECO()
        await (await ecoPage.Buyer).isDisplayed()
        console.log("Buyer is availbale on ECO page")
        await (await ecoPage.Seller).isDisplayed()
        console.log("Seller is availbale on ECO page")
        await (await ecoPage.Technician).isDisplayed()
        console.log("Technician is availbale on ECO page")
        await(await ecoPage.Buyer).click()
        console.log("Clicked on Buyer")
        expect(await ecoPage.Check_Repair_Estimate).toBeDisplayed()
        console.log("Check Repair Estimate is displayed")
        await(await ecoPage.Check_Repair_Estimate).click()
        console.log("Clicked on Check Repair Estimate")
        await(await ecoPage.checkRepairEstiHeading).waitForDisplayed({timeout:15000})
        expect(await ecoPage.checkRepairEstiHeading).toBeDisplayed()
        console.log("Heading is displayed as : "+await(await ecoPage.checkRepairEstiHeading).getText())
        await base.scrollToExactText("Select Make")
        expect(await ecoPage.make1).toBeDisplayed()
        console.log("Select Make is Displayed")
        await(await ecoPage.make1).click()
        console.log("Clicked on Make")
        await(await ecoPage.MakeName).click()
        console.log("Selected the Make Name")
        await(await ecoPage.model1).click()
        console.log("Clicked on Model")
        await(await ecoPage.ModelName).click()
        console.log("Selected the Model Name")
        await(await ecoPage.Trim1).click()
        console.log("Clicked on the Trim Field")
        await(await ecoPage.TrimTo).click()
        console.log("Selected trim to option")
        await(await ecoPage.location).click()
        console.log("Clicked on the Location")
        await(await ecoPage.myLocation).click()
        console.log("Clicked on the Location")
        await(await ecoPage.MyLocation).setValue("Delhi")
        console.log("Set the location")
        await(await ecoPage.delhi).click()
        await(await ecoPage.Next).click()
        expect(await ecoPage.repairServiceHeading).isDisplayed()
        console.log("Heading is displayed as : "+await(await ecoPage.repairServiceHeading ).getText())
        await(await ecoPage.airFilter).click()
        await Base.swipeUp()
        await(await ecoPage.getEstimate).click()
        expect(await ecoPage.Estimated_RepairCost).isDisplayed()
        console.log(await(await ecoPage.Estimated_RepairCost).getText())
    }); 
    it('TC_04 Verify Features on ECO for Four Wheelers', async () => {
        await browser.url('/user/login')
        await  ecoPage.traverseToECO()
        await (await ecoPage.Seller).isDisplayed()
        console.log("Seller is availbale on ECO page")
        await (await ecoPage.Seller).click()
        expect(ecoPage.RegiAsVendor).toBeDisplayed()
        console.log("Register As a Vendor is Displayed")
        await (await ecoPage.RegiAsVendor).click()
        console.log("Clicked on Resister as Vendor")
        await(await ecoPage.hamburgurOnEco).click()
        console.log("Traversing to the Features , SIgn Up, Services")
        await (await ecoPage.features).click()
        console.log("Clicked on Features")
        expect(await ecoPage.features_FourWheelers).toBeDisplayed()
        console.log("ECO inspection Page is Displayed for Four wheelers")
        expect(await ecoPage.chechPoint_FourWheeler).toBeDisplayed()
        console.log("checkpoint for four wheelers are displayed")
        expect(await ecoPage.assessment).toBeDisplayed()
        console.log(await (ecoPage.assessment).getText())
        console.log("Inspection Checkpoints for Four Wheeler Displayed");
    });
    it('TC_05 Verify Features on ECO for Two Wheelers', async () => {
       await browser.url('/user/login')
        expect(await ecoPage.featurs_TwoWheelers).toBeDisplayed()
        await(await ecoPage.featurs_TwoWheelers).click()
        console.log("Clicked on Two Wheelers");
        expect(await ecoPage.chechPoint_TwoWheeler).toBeDisplayed()
        console.log(await (await ecoPage.chechPoint_TwoWheeler).getText())
        console.log("Check Points for Two Wheeler displayed")
        expect(await ecoPage.tires_Wheels).toBeDisplayed()
        console.log(await (await ecoPage.tires_Wheels).getText())
    });
    it('TC_06 Verify Car Inspection Service on Eco', async () => {
         await browser.url('/user/login')
        expect(await ecoPage.ECO_Offering).toBeDisplayed()
        console.log("ECO Offering Heading displayed for Cars and the Bikes")
        expect(await ecoPage.Cars).toBeDisplayed()
        console.log("Cars option available under ECO offering")
        expect(await ecoPage.inspectionServices).toBeDisplayed()
        console.log("Inspection services displayed under ECO Offering")
        expect(await ecoPage.basicInspection).toBeDisplayed()
        console.log("Basic inspection is shown")
        await(await ecoPage.cars).click()
        console.log("Clicked On Cars Category")
        expect(await ecoPage.basicAmt).toBeDisplayed()
        console.log("Basic inspection Amount is shown")
        console.log(await (await ecoPage.basicAmt).getText())
        Base.swipeUp()
        expect(await ecoPage.premiumAmt).toBeDisplayed()
        console.log("Premium inspection is Shown")
        console.log(await (await ecoPage.premiumAmt).getText())
        expect(await ecoPage.premiumPlusAmt).toBeDisplayed()
        Base.scrollToTextContain("Premium")
        console.log("Premium plus Inspection shown")
        console.log(await (await ecoPage.premiumPlusAmt).getText())
        expect(await ecoPage.viewSampleReport).toBeDisplayed()
        console.log("Link to Download Sample report is displayed")
    });
    it('TC_07 Verify Bike Inspection  Service on ECO', async () => {
        await browser.url('/user/login')
        await ecoPage.traverseToECO()
        expect(await ecoPage.ECO_Offering).toBeDisplayed()
        console.log("ECO Offering Heading displayed for Cars and the Bikes")
        expect(await ecoPage.Bikes).toBeDisplayed()
        console.log("Bikes option available under ECO offering")
        expect(await ecoPage.inspectionServices).toBeDisplayed()
        console.log("Inspection services displayed under ECO Offering")
        await(await ecoPage.Bikes).click()
        console.log("CLicked on Bikes Category")
        expect(await ecoPage.basicInspection).toBeDisplayed()
        console.log("Basic inspection is shown")
        Base.swipeUp()
        expect(await ecoPage.basicAmtBike).toBeDisplayed()
        console.log("Basic inspection Amount for Bike is shown")
        console.log(await (await ecoPage.basicAmtBike).getText())
        Base.scrollToExactText("Premium Inspection")
        expect(await ecoPage.premiumAmtBike).toBeDisplayed()
        console.log("Premium inspection for Bike is Shown")
        console.log(await (await ecoPage.premiumAmtBike).getText())
        Base.scrollToExactText("Title Certificate")
        expect(await ecoPage.titleCertificate).toBeDisplayed()
        console.log("Premium plus Inspection Under Title Certificate is shown")
        console.log(await (await ecoPage.titleCertificate).getText())
        expect(await ecoPage.viewSampleReport).toBeDisplayed()
        expect(await ecoPage.titleAmt).toBeDisplayed()
        console.log("Title Certificate Amount is Shown")
        console.log(await (await ecoPage.titleAmt).getText())
        console.log("Link to Download Sample report is displayed")
    });*/
    it('TC_08 Verify scooter Inspection  Service on Eco', async () => {
        await browser.url('/user/login')
        await ecoPage.traverseToECO()
        await (await ecoPage.seller).click()
        expect(ecoPage.RegiAsVendor).toBeDisplayed()
        console.log("Register As a Vendor is Displayed")
        await (await ecoPage.RegiAsVendor).waitForEnabled({ timeout: 1500 })
        await (await ecoPage.RegiAsVendor).click()
        console.log("Clicked on Resister as Vendor")
        await(await ecoPage.hamburgurOnEco).click()
        console.log("Traversing to the Services,Features,Sign up Options")
        expect(await ecoPage.service).toBeDisplayed()
        console.log("After click on Hamburger Menu Services tab is shown")
        await (await ecoPage.services).click()
        await (await ecoPage.scooterInspection).click()
        console.log("Clicked on Scooter Inspection")
        expect(await ecoPage.scooterInspectionHeading).toBeDisplayed()
        console.log("Scooter Inspection Heading is shown")
        expect(await ecoPage.scooterInspectionHeading).toHaveTextContaining("Get A Used Scooter Inspection With ECO")
        console.log(await (await ecoPage.scooterInspectionHeading).getText())
        expect(await ecoPage.bookInspection).toBeDisplayed()
        console.log("Book Insoection Button is show")
    });
    it('TC_09 Verify Sign up functionality on ECO', async () => {
        await browser.url('/user/login')
        await ecoPage.traverseToECO()
        await (await ecoPage.Seller).click()
        await browser.pause(3000)
        expect(ecoPage.RegiAsVendor).toBeDisplayed()
        console.log("Register As a Vendor is Displayed")
        await (await ecoPage.RegiAsVendor).waitForEnabled({ timeout: 1500 })
        await (await ecoPage.RegiAsVendor).click()
        console.log("Clicked on Resister as Vendor")
        await(await ecoPage.hamburgurOnEco).click()
        console.log("Traversing to the Services,Features,Sign up Options")
        expect(await ecoPage.signUp).toBeDisplayed()
        await(await ecoPage.signUp).click()
        console.log("Clicked on Sign Up Functionality")
        expect(await ecoPage.signUpHeading).toBeDisplayed()
        console.log(await (await signUpHeading).getText())     
    });
    it('TC_10 Verify Watch ECO TV functionality', async () => {
        await browser.url('/user/login')
        await ecoPage.traverseToECO()
        await (await ecoPage.Technician).click()
        await browser.pause(3000)
        expect(ecoPage.RegiAsTechnician).toBeDisplayed()
        console.log("Register As a Technician is Displayed")
        await (await ecoPage.RegiAsTechnician).click()
        console.log("Clicked on Resister as Technician")
        await (await ecoPage.createUrAccount).waitForDisplayed({ timeout: 1500 })
        await(await ecoPage.hamburgurOnEco).click()
        console.log("Traversing to the Services,Features,Sign up Options")
        expect(await ecoPage.watchEcoTv).toBeDisplayed()
        console.log("Watch Eco TV option displayed")
        await(await ecoPage.watchEcoTv).click()
        console.log("CLicked on Watch ECO TV")
        expect(await ecoPage.videoHeading).toBeDisplayed()
        concole.log("Video is displayed")
        expect(await ecoPage.closeVideo).toBeDisplayed()
        concole.log("Close Button is displayed to close the video")
});
});