const base = require("../../BaseClass/base");
const requirementsVerificationPage = require("../../Pages/Androidbrowser/requirementsVerificationPage");
describe('Requirements Verification', async () => {
    beforeEach(async () => {
        await driver.closeApp()
        await driver.launchApp()
    });
    it('TC_01 Validate all requirements created userLogin are displayed', async () => {
        browser.url('/user/login')
        await base.androidBrowserLoginAsBuyer()
        expect(await requirementsVerificationPage.welcomemsg).toBeDisplayed()
        console.log(await (await requirementsVerificationPage.welcomemsg).getText())
        console.log("Buyer login Successfully")
        await browser.pause(2000)
        await base.swipeUp()
        await (await requirementsVerificationPage.my_Requirements).click()
        console.log("Clicked On My Requirements")
        await (await requirementsVerificationPage.Add_New_Requirement).waitForDisplayed({ timeout: 20000 })
        expect(await requirementsVerificationPage.requirements).toBeDisplayed()
        console.log("All Requirements Created Displayed")
        console.log(await (await requirementsVerificationPage.requirements).getText())
       // browser.url('/home')
       //await base.logoutandroidBrowserBuyer()
    });

    it('TC_02 Verify requirements score is a display', async () => {
        browser.url('/account')
        await browser.pause('4000')
       //browser.url('/user/login')
       // await base.androidBrowserLoginAsBuyer()
       expect(await requirementsVerificationPage.welcomemsg).toBeDisplayed()
        console.log(await (await requirementsVerificationPage.welcomemsg).getText())
        console.log("Buyer login Successfully")
        await base.swipeUp()
        await (await requirementsVerificationPage.my_Requirements).click()
        console.log("Clicked On My Requirements")
        await (await requirementsVerificationPage.Add_New_Requirement).waitForDisplayed({ timeout: 20000 })
        expect(await requirementsVerificationPage.Score).toBeDisplayed()
        console.log("Score Displayed")
        console.log(await (await requirementsVerificationPage.Score).getText())
        console.log(await (await requirementsVerificationPage.Score_Count).getText())
       // browser.url('/home')
       // await base.logoutandroidBrowserBuyer()
    });

   it('TC_03 Verify requirements name is editable', async () => {
        //browser.url('/user/login')
        browser.url('/account')
        await browser.pause('4000')
      //  await base.androidBrowserLoginAsBuyer()
        expect(await requirementsVerificationPage.welcomemsg).toBeDisplayed()
        console.log(await (await requirementsVerificationPage.welcomemsg).getText())
        console.log("Buyer login Successfully")
        await base.swipeUp()
        await (await requirementsVerificationPage.my_Requirements).click()
        console.log("Clicked on My Requirements")
        await (await requirementsVerificationPage.Add_New_Requirement).waitForDisplayed({ timeout: 20000 })
        await (await requirementsVerificationPage.search).click()
        expect(await requirementsVerificationPage.search).toBeDisplayed()
        console.log("Requirements Name Is Editable")
        //browser.url('/home')
       // await base.logoutandroidBrowserBuyer()
    });

    it('TC_04 Verify Add New Requirements link is available', async () => {
        //browser.url('/user/login')
      //  await base.androidBrowserLoginAsBuyer()
      browser.url('/account')
      await browser.pause('4000')
        expect(await requirementsVerificationPage.welcomemsg).toBeDisplayed()
        console.log(await (await requirementsVerificationPage.welcomemsg).getText())
        console.log("Buyer login Successfully")
        await base.swipeUp()
        await (await requirementsVerificationPage.my_Requirements).click()
        console.log("Clicked On My Requirements")
        await (await requirementsVerificationPage.Add_New_Requirement).waitForDisplayed({ timeout: 20000 })
        expect(await requirementsVerificationPage.Add_New_Requirement).toBeDisplayed()
        console.log("+ Add New Requirements Link Is Available")
        console.log(await (await requirementsVerificationPage.Add_New_Requirement).getText())
      //  browser.url('/home')
       // await base.logoutandroidBrowserBuyer()
    });
   it('TC_05 Verify all static contents are display', async () => {
    browser.url('/account')
    await browser.pause('4000')
        expect(await requirementsVerificationPage.welcomemsg).toBeDisplayed()
        console.log(await (await requirementsVerificationPage.welcomemsg).getText())
        console.log("Buyer login Successfully")
        await base.swipeUp()
        await (await requirementsVerificationPage.my_Requirements).click()
        console.log("Clicked On My Requirements")
        expect(await requirementsVerificationPage.Add_New_Requirement).toBeDisplayed()
        console.log(await (await requirementsVerificationPage.Add_New_Requirement).getText())
        console.log(await (await requirementsVerificationPage.Score).getText())
        console.log(await (await requirementsVerificationPage.Score_Count).getText())
        expect(await requirementsVerificationPage.requirements).toBeDisplayed()
        console.log(await (await requirementsVerificationPage.requirements).getText())
        expect(await requirementsVerificationPage.Price_Range).toBeDisplayed()
        console.log(await (await requirementsVerificationPage.Price_Range).getText())
        expect(await requirementsVerificationPage.Used).toBeDisplayed()
        console.log("Vehicle Condition Displayed")
        expect(await requirementsVerificationPage.any).toBeDisplayed()
        expect(await requirementsVerificationPage.best_Matches).toBeDisplayed()
        console.log(await (await requirementsVerificationPage.best_Matches).getText())
        console.log("Best Matches Count Displayed")
        expect(await requirementsVerificationPage.my_Matches).toBeDisplayed()
        console.log(await (await requirementsVerificationPage.my_Matches).getText())
        console.log("My Matches Count Displayed")
      //  browser.url('/home')
       // await base.logoutandroidBrowserBuyer()
    });
    it('TC_06 Verify payments status of requirements are display ', async () => {
        browser.url('/account')
      await browser.pause('4000')
        expect(await requirementsVerificationPage.welcomemsg).toBeDisplayed()
        console.log(await (await requirementsVerificationPage.welcomemsg).getText())
        console.log("Buyer login Successfully")
        await base.swipeUp()
        await (await requirementsVerificationPage.my_Requirements).click()
        await (await requirementsVerificationPage.Add_New_Requirement).waitForDisplayed({ timeout: 20000 })
        expect(await requirementsVerificationPage.Unlock_Fee_Payment).toBeDisplayed()
        console.log(await (await requirementsVerificationPage.Unlock_Fee_Payment).getText())
        console.log("Payments Status Of Requirement Are Displayed")
       // browser.url('/home')
      //  await base.logoutandroidBrowserBuyer()
    });
});