const base = require('../../BaseClass/base');
const UsedCarPage = require('../../Pages/Androidbrowser/usedCarPage');

  describe('Used Car', () => {
    beforeEach(async () => {
        await driver.closeApp()
        await driver.launchApp()
    });
 it('TC_01 Verify car option is the display with used Condition to the buyer', async () => {
    await base.androidBrowserLoginAsBuyer()
    console.log("logeed is as Buyer")
    await browser.pause("1000")
   // await (await UsedCarPage.menu).click()
    //console.log("clicked on Menu")
    await base.swipeUp()
     expect (await UsedCarPage.myReq).toBeDisplayed()
    console.log("my Requirement is displayed")
    await (await UsedCarPage.myReq).click()
    console.log("Clicked on my Requirement")
    await browser.pause(8000)
    await (await UsedCarPage.addNewReq).waitForDisplayed({timeout:10000})
    expect (await UsedCarPage.addNewReq).toBeDisplayed()
    console.log("Add New Requirement is displayed")
    await (await UsedCarPage.addNewReq).click()
    console.log("Clicked on Add New Requirement")
    expect(await UsedCarPage.caroption).toBeDisplayed()
    console.log('Car option displayed')
    expect(await UsedCarPage.scooteroption).toBeDisplayed()
    console.log('scooter option displayed')
    expect(await UsedCarPage.newRadio).toBeDisplayed()
    console.log('New Condition option displayed')
    expect(await UsedCarPage.usedRadio).toBeDisplayed()
    console.log('Used Condition option displayed')
    expect(await UsedCarPage.location).toBeDisplayed()
    console.log('Location displayed')
    expect(await UsedCarPage.searchLocation).toBeDisplayed()
    console.log('search my location displayed')
    expect(await UsedCarPage.nextBtn).toBeDisplayed()
    console.log('Next Button displayed')
    });
    
    it('TC_02 Verify user able to select location using location option', async () => {
     await base.androidBrowserLoginAsBuyer()
    console.log("logeed is as Buyer")
    await browser.pause("1000")
   // await (await UsedCarPage.menu).click()
    //console.log("clicked on Menu")
    await base.swipeUp()
     expect (await UsedCarPage.myReq).toBeDisplayed()
    console.log("my Requirement is displayed")
    await (await UsedCarPage.myReq).click()
    console.log("Clicked on my Requirement")
    await browser.pause(8000)
    await (await UsedCarPage.addNewReq).waitForDisplayed({timeout:10000})
    expect (await UsedCarPage.addNewReq).toBeDisplayed()
    console.log("Add New Requirement is displayed")
    await (await UsedCarPage.addNewReq).click()
    console.log("Clicked on Add New Requirement")
    expect(await UsedCarPage.caroption).toBeDisplayed()
    console.log('Car option displayed')
    expect(await UsedCarPage.searchLocation).toBeDisplayed()
    console.log('search my location displayed')
    await (await UsedCarPage.textFieldLocation).click()
    console.log("clicked on search my location")
     //await (await UsedCarPage.TypeToLocation).click()
    //console.log("CLicked On Type to Location")
    await (await UsedCarPage.textFieldLocation).setValue("Delhi,India")
    await (await UsedCarPage.cityName).click()
    console.log("selected city")
    await (await UsedCarPage.nextBtn).click()
    console.log("Clicked on Next Button")
    expect(await UsedCarPage.heading2).toBeDisplayed()
    console.log(await (await UsedCarPage.heading2).getText())
    console.log("User able to select location and navigate to next window")
   });
   it('TC_03 Verify error message without entering location', async () => {
    await base.androidBrowserLoginAsBuyer()
    console.log("logeed is as Buyer")
    await browser.pause("1000")
    await base.swipeUp()
   // await (await UsedCarPage.menu).click()
    //console.log("clicked on Menu")
    expect (await UsedCarPage.myReq).toBeDisplayed()
    console.log("my Requirement is displayed")
    await (await UsedCarPage.myReq).click()
    console.log("Clicked on my Requirement")
    await browser.pause(8000)
    await (await UsedCarPage.addNewReq).waitForDisplayed({timeout:10000})
    expect (await UsedCarPage.addNewReq).toBeDisplayed()
    console.log("Add New Requirement is displayed")
    await (await UsedCarPage.addNewReq).click()
    console.log("Clicked on Add New Requirement")
    expect(await UsedCarPage.caroption).toBeDisplayed()
    console.log('Car option displayed')
    expect(await UsedCarPage.searchLocation).toBeDisplayed()
    console.log('search my location displayed')
    await (await UsedCarPage.nextBtn).click()
    console.log("Clicked On Next Button")
    expect(await UsedCarPage.errormsg).toBeDisplayed()
    console.log('error message displayed')
   });
   
 it('TC_04 Verify user able to select car model from Entering your vehicle details as per requirement', async () => {
    await base.androidBrowserLoginAsBuyer()
    console.log("logeed is as Buyer")
    await browser.pause("1000")
   // await (await UsedCarPage.menu).click()
    //console.log("clicked on Menu")
     await base.swipeUp()
    expect (await UsedCarPage.myReq).toBeDisplayed()
    console.log("my Requirement is displayed")
    await (await UsedCarPage.myReq).click()
    console.log("Clicked on my Requirement")
    await browser.pause(8000)
    await (await UsedCarPage.addNewReq).waitForDisplayed({timeout:10000})
    expect (await UsedCarPage.addNewReq).toBeDisplayed()
    console.log("Add New Requirement is displayed")
    await (await UsedCarPage.addNewReq).click()
    console.log("Clicked on Add New Requirement")
    expect(await UsedCarPage.caroption).toBeDisplayed()
    console.log('Car option displayed')
    await (await UsedCarPage.textFieldLocation).setValue("Pune, Maharashtra, India")
    await (await UsedCarPage.pune).click()
    console.log("selected city")
    await (await UsedCarPage.nextBtn).click()
    expect(await UsedCarPage.heading2).toBeDisplayed()
    console.log(await (await UsedCarPage.heading2).getText())
    expect(await UsedCarPage.subHeading).toBeDisplayed()
    console.log(await (await UsedCarPage.subHeading).getText())
    expect(await UsedCarPage.enterVehicleHeading).toBeDisplayed()
    console.log(await (await UsedCarPage.enterVehicleHeading).getText())
    expect(await UsedCarPage.searchField).toBeDisplayed()
    console.log("search field displayed")
    await (await UsedCarPage.searchField).setValue("Maruti Suzuki Ertiga VDi 2015")
    await (await UsedCarPage.car1).click()
    console.log("User can select Car using Search Field")
   });
   it('TC_05 Verify user able to select car model through select from the dropdown as per requirement', async () => {
    await base.androidBrowserLoginAsBuyer()
    console.log("logeed is as Buyer")
    await browser.pause("1000")
   // await (await UsedCarPage.menu).click()
    //console.log("clicked on Menu")
    await base.swipeUp()
     expect (await UsedCarPage.myReq).toBeDisplayed()
    console.log("my Requirement is displayed")
    await (await UsedCarPage.myReq).click()
    console.log("Clicked on my Requirement")
    await browser.pause(8000)
    await (await UsedCarPage.addNewReq).waitForDisplayed({timeout:10000})
    expect (await UsedCarPage.addNewReq).toBeDisplayed()
    console.log("Add New Requirement is displayed")
    await (await UsedCarPage.addNewReq).click()
    console.log("Clicked on Add New Requirement")
    expect(await UsedCarPage.caroption).toBeDisplayed()
    console.log("Car option displayed")
    await (await UsedCarPage.currentLocation).click()
    console.log("CLicked on CUrrent Location")
    expect(await UsedCarPage.heading1).toBeDisplayed()
    await (await UsedCarPage.nextBtn).click()
    console.log("Clicked on Next")
    expect(await UsedCarPage.heading2).toBeDisplayed()
    console.log(await (await UsedCarPage.heading2).getText())
    browser.pause('2000')
    expect(await UsedCarPage.subHeading).toBeDisplayed()
    console.log(await (await UsedCarPage.subHeading).getText())
    expect(await UsedCarPage.selectFromDropDown).toBeDisplayed()
    console.log("Select From DropDown is Displayed")
    await(await UsedCarPage.selectFromDropDown).click()
    console.log("CLicked On Select From Drop Down")
    await UsedCarPage.selectVehicleFromDropdown()
    await (await UsedCarPage.nextBtn).click()
    expect(await UsedCarPage.heading3).toBeDisplayed()
    console.log(await (await UsedCarPage.heading3).getText())
    console.log('successfully Car selected from dropdown')
   });
 it('TC_06 Verify user able to select car model through Let Droom Suggest for you as per requirement', async () => {
   await base.androidBrowserLoginAsBuyer()
    console.log("logeed is as Buyer")
    await browser.pause("1000")
   // await (await UsedCarPage.menu).click()
    //console.log("clicked on Menu")
    await base.swipeUp()
     expect (await UsedCarPage.myReq).toBeDisplayed()
    console.log("my Requirement is displayed")
    await (await UsedCarPage.myReq).click()
    console.log("Clicked on my Requirement")
    await browser.pause(8000)
    await (await UsedCarPage.addNewReq).waitForDisplayed({timeout:10000})
    expect (await UsedCarPage.addNewReq).toBeDisplayed()
    console.log("Add New Requirement is displayed")
    await (await UsedCarPage.addNewReq).click()
    console.log("Clicked on Add New Requirement")
    expect(await UsedCarPage.caroption).toBeDisplayed()
    console.log("Car option displayed")
    await (await UsedCarPage.currentLocation).click()
    console.log("CLicked on CUrrent Location")
    expect(await UsedCarPage.heading1).toBeDisplayed()
    await (await UsedCarPage.nextBtn).click()
    console.log("Clicked on Next")
    expect(await UsedCarPage.heading2).toBeDisplayed()
    console.log(await (await UsedCarPage.heading2).getText())
    browser.pause('2000')
    expect(await UsedCarPage.subHeading).toBeDisplayed()
    expect(await UsedCarPage.droomSuggest).toBeDisplayed()
    console.log('Droom suggest displayed')
    await (await UsedCarPage.droomSuggest).click()
    console.log("clicked on droom suggest for you")
    expect(await UsedCarPage.budget).toBeDisplayed()
    console.log('Price range displayed')
    expect(await UsedCarPage.bodyType).toBeDisplayed()
    console.log('body type displayed')
    await UsedCarPage.droomSuggestCar()
    expect(await UsedCarPage.heading6).toBeDisplayed()
    console.log(await (await UsedCarPage.heading6).getText())
    //await (await UsedCarPage.vehicle1).click()
    await (await UsedCarPage.nextBtn).click()
    expect(await  UsedCarPage.budget).toBeDisplayed()
    console.log('What is Your Budget? option Display')
    console.log('user able to select bike from droom suggest')
   });
   it('TC_07 Verify user able to select used car as per the budget', async () => {
    
     await base.androidBrowserLoginAsBuyer()
    console.log("logeed is as Buyer")
    await browser.pause("1000")
   // await (await UsedCarPage.menu).click()
    //console.log("clicked on Menu")
    await base.swipeUp()
     expect (await UsedCarPage.myReq).toBeDisplayed()
    console.log("my Requirement is displayed")
    await (await UsedCarPage.myReq).click()
    console.log("Clicked on my Requirement")
    await browser.pause(8000)
    await (await UsedCarPage.addNewReq).waitForDisplayed({timeout:10000})
    expect (await UsedCarPage.addNewReq).toBeDisplayed()
    console.log("Add New Requirement is displayed")
    await (await UsedCarPage.addNewReq).click()
    console.log("Clicked on Add New Requirement")
    expect(await UsedCarPage.caroption).toBeDisplayed()
    console.log("Car option displayed")
    await (await UsedCarPage.currentLocation).click()
    console.log("CLicked on CUrrent Location")
    expect(await UsedCarPage.heading1).toBeDisplayed()
    await (await UsedCarPage.nextBtn).click()
    console.log("Clicked on Next")
    expect(await UsedCarPage.heading2).toBeDisplayed()
    console.log(await (await UsedCarPage.heading2).getText())
    browser.pause('2000')
    expect(await UsedCarPage.subHeading).toBeDisplayed()
    expect(await UsedCarPage.droomSuggest).toBeDisplayed()
    console.log('Droom suggest displayed')
    await (await UsedCarPage.droomSuggest).click()
    console.log("clicked on droom suggest for you")
    expect(await UsedCarPage.budget).toBeDisplayed()
    console.log('Price range displayed')
    expect(await UsedCarPage.bodyType).toBeDisplayed()
    console.log('body type displayed')
    await UsedCarPage.droomSuggestCar()
    expect(await UsedCarPage.heading6).toBeDisplayed()
    console.log(await (await UsedCarPage.heading6).getText())
    //await (await UsedCarPage.vehicle1).click()
    await (await UsedCarPage.nextBtn).click()
    expect(await  UsedCarPage.budget).toBeDisplayed()
    console.log('What is Your Budget? option Display')
    console.log('user able to select bike from droom suggest')
    console.log('Price range displayed')
    await browser.touchAction([
     { action: 'press', x: 200, y: 200 },
     { action: 'moveTo', x: 200, y: 300 },
     'release'
    ])
    console.log("price slider displayed")
    await (await UsedCarPage.nextBtn).click()
    console.log("clicked on Next1 button")
    await (await UsedCarPage.nextBtn).click()
    await browser.pause('2000')
    console.log("clicked on Next2 button")
    await (await UsedCarPage.nextBtn).click()
    await browser.pause('2000')
    console.log("clicked on Next3 button")
    await (await UsedCarPage.nextBtn).click()
    console.log("clicked on Next4 button")


    await (await UsedCarPage.submitBtn).click()
    await (await UsedCarPage.submitViewMatch).click()
    await (await UsedCarPage.allrequirement).click()
    //expect(await UsedCarPage.priceRange).toBeDisplayed()
    console.log("price Range displayed")
    });
 
   it('TC_08 Verify user able to select use car as per the Fuel type', async () => {
     await base.androidBrowserLoginAsBuyer()
    console.log("logeed is as Buyer")
    await browser.pause("1000")
   // await (await UsedCarPage.menu).click()
    //console.log("clicked on Menu")
    await base.swipeUp()
     expect (await UsedCarPage.myReq).toBeDisplayed()
    console.log("my Requirement is displayed")
    await (await UsedCarPage.myReq).click()
    console.log("Clicked on my Requirement")
    await browser.pause(8000)
    await (await UsedCarPage.addNewReq).waitForDisplayed({timeout:10000})
    expect (await UsedCarPage.addNewReq).toBeDisplayed()
    console.log("Add New Requirement is displayed")
    await (await UsedCarPage.addNewReq).click()
    console.log("Clicked on Add New Requirement")
    expect(await UsedCarPage.caroption).toBeDisplayed()
    console.log("Car option displayed")
    await (await UsedCarPage.currentLocation).click()
    console.log("CLicked on CUrrent Location")
    expect(await UsedCarPage.heading1).toBeDisplayed()
    await (await UsedCarPage.nextBtn).click()
    console.log("Clicked on Next")
    expect(await UsedCarPage.heading2).toBeDisplayed()
    console.log(await (await UsedCarPage.heading2).getText())
    browser.pause('2000')
    expect(await UsedCarPage.subHeading).toBeDisplayed()
    expect(await UsedCarPage.droomSuggest).toBeDisplayed()
    console.log('Droom suggest displayed')
    await (await UsedCarPage.droomSuggest).click()
    console.log("clicked on droom suggest for you")
    expect(await UsedCarPage.budget).toBeDisplayed()
    console.log('Price range displayed')
    expect(await UsedCarPage.bodyType).toBeDisplayed()
    console.log('body type displayed')
    await UsedCarPage.droomSuggestCar()
    expect(await UsedCarPage.heading6).toBeDisplayed()
    console.log(await (await UsedCarPage.heading6).getText())
    //await (await UsedCarPage.vehicle1).click()
    await (await UsedCarPage.nextBtn).click()
    await browser.pause("2000")
    await (await UsedCarPage.nextBtn).click()

    expect(await UsedCarPage.fuelType).toBeDisplayed()
    expect(await UsedCarPage.fuel).toBeDisplayed()
    console.log(await (await UsedCarPage.fuel).getText())
    await (await UsedCarPage.fueltoggle).click()
    await browser.pause("2000")
    await (await UsedCarPage.nextBtn).click()
    await browser.pause("2000")
    await (await UsedCarPage.nextBtn).click()
    await browser.pause("2000")
    await (await UsedCarPage.nextBtn).click()
    await browser.pause("2000")
    await (await UsedCarPage.nextBtn).click()
    await (await UsedCarPage.submitBtn).click()
    await (await UsedCarPage.submitViewMatch).click()
    await (await UsedCarPage.allrequirement).click()
    console.log("user able to select fuel type")
  });
 it('TC_09 Verify user able to select used car as per the KMS Driven Range',async () =>{
   await base.androidBrowserLoginAsBuyer()
    console.log("logeed is as Buyer")
    await browser.pause("1000")
   // await (await UsedCarPage.menu).click()
    //console.log("clicked on Menu")
    await base.swipeUp()
     expect (await UsedCarPage.myReq).toBeDisplayed()
    console.log("my Requirement is displayed")
    await (await UsedCarPage.myReq).click()
    console.log("Clicked on my Requirement")
    await browser.pause(8000)
    await (await UsedCarPage.addNewReq).waitForDisplayed({timeout:10000})
    expect (await UsedCarPage.addNewReq).toBeDisplayed()
    console.log("Add New Requirement is displayed")
    await (await UsedCarPage.addNewReq).click()
    console.log("Clicked on Add New Requirement")
    expect(await UsedCarPage.caroption).toBeDisplayed()
    console.log("Car option displayed")
    await (await UsedCarPage.currentLocation).click()
    console.log("CLicked on CUrrent Location")
    expect(await UsedCarPage.heading1).toBeDisplayed()
    await (await UsedCarPage.nextBtn).click()
    console.log("Clicked on Next")
    expect(await UsedCarPage.heading2).toBeDisplayed()
    console.log(await (await UsedCarPage.heading2).getText())
    browser.pause('2000')
    expect(await UsedCarPage.subHeading).toBeDisplayed()
    expect(await UsedCarPage.droomSuggest).toBeDisplayed()
    console.log('Droom suggest displayed')
    await (await UsedCarPage.droomSuggest).click()
    console.log("clicked on droom suggest for you")
    expect(await UsedCarPage.budget).toBeDisplayed()
    console.log('Price range displayed')
    expect(await UsedCarPage.bodyType).toBeDisplayed()
    console.log('body type displayed')
    await UsedCarPage.droomSuggestCar()
    expect(await UsedCarPage.heading6).toBeDisplayed()
    console.log(await (await UsedCarPage.heading6).getText())
    //await (await UsedCarPage.vehicle1).click()
    await (await UsedCarPage.nextBtn).click()
    await browser.pause("2000")
    await (await UsedCarPage.nextBtn).click()
    expect(await UsedCarPage.kmDrivenRange).toBeDisplayed()
    console.log("KM Driven Range Displayed")
    await (await UsedCarPage.nextBtn).click()
    await browser.pause("2000")
    await (await UsedCarPage.nextBtn).click()
    await browser.pause("2000")
    await (await UsedCarPage.nextBtn).click()
    await browser.pause("2000")
    await (await UsedCarPage.nextBtn).click()
    await (await UsedCarPage.submitBtn).click()
    await (await UsedCarPage.submitViewMatch).click()
    await (await UsedCarPage.allrequirement).click()
    console.log("KM Range displayed")

  });
  it('TC_10 Verify user able to select use car as per the Exterior Color', async () => {
    await base.androidLoginAsBuyer()
    await (await UsedCarPage.buy).click()
    await (await UsedCarPage.carimg).click() 
    await (await UsedCarPage.caroption).click()
    await (await UsedCarPage.searchLocation).click()
    await (await UsedCarPage.cityName).click()
    console.log("selected city")
    await (await UsedCarPage.nextBtn).click()
    expect(await UsedCarPage.subHeading).toBeDisplayed()
    console.log(await (await UsedCarPage.subHeading).getText())
    expect(await UsedCarPage.selectVehicle).toBeDisplayed()
    await (await UsedCarPage.selectVehicle).click()
    await UsedCarPage.selectVehicleFromDropdown()
    await (await UsedCarPage.nextBtn).click()
    await browser.pause('2000')
    await (await UsedCarPage.nextBtn).click()
    
    expect(await UsedCarPage.extColor).toBeDisplayed()
    await (await UsedCarPage.color1).click()
    await (await UsedCarPage.nextBtn).click()
    await browser.pause('2000')
    await (await UsedCarPage.nextBtn).click()
    await browser.pause('2000')
    await (await UsedCarPage.nextBtn).click()
    await browser.pause('2000')
    await (await UsedCarPage.submitBtn).click()
    await (await UsedCarPage.submitViewMatch).click()
    await (await UsedCarPage.allrequirement).click()
    console.log("Exterior color displayed")
  });

  it('TC_11 Verify user able to select use car as per the Transmission Type', async () => {
    await base.androidLoginAsBuyer()
    await (await UsedCarPage.buy).click()
    await (await UsedCarPage.carimg).click() 
    await (await UsedCarPage.caroption).click()
    await (await UsedCarPage.searchLocation).click()
    await (await UsedCarPage.cityName).click()
    console.log("selected city")
    await (await UsedCarPage.nextBtn).click()
    expect(await UsedCarPage.subHeading).toBeDisplayed()
    console.log(await (await UsedCarPage.subHeading).getText())
    expect(await UsedCarPage.selectVehicle).toBeDisplayed()
    await (await UsedCarPage.selectVehicle).click()
    await UsedCarPage.selectVehicleFromDropdown()
    await (await UsedCarPage.nextBtn).click()
    await browser.pause('2000')
    await (await UsedCarPage.nextBtn).click()

    expect(await UsedCarPage.transmissionType).toBeDisplayed()
    await (await UsedCarPage.type1).click()
    await browser.pause('2000')
    await (await UsedCarPage.nextBtn).click()
    await browser.pause('2000')
    await (await UsedCarPage.nextBtn).click()
    await browser.pause('2000')
    await (await UsedCarPage.nextBtn).click()
    await browser.pause('2000')
    await (await UsedCarPage.nextBtn).click()
    await (await UsedCarPage.submitBtn).click()
    await (await UsedCarPage.submitViewMatch).click()
    await (await UsedCarPage.allrequirement).click()
    console.log("Transmission Type displayed")
  });

   it('TC_12 Verify user able to select use car as per the Do you also need option', async () => {
    await base.androidLoginAsBuyer()
    await (await UsedCarPage.buy).click()
    await (await UsedCarPage.carimg).click() 
    await (await UsedCarPage.caroption).click()
    await (await UsedCarPage.searchLocation).click()
    await (await UsedCarPage.cityName).click()
    console.log("selected city")
    await (await UsedCarPage.nextBtn).click()
    expect(await UsedCarPage.subHeading).toBeDisplayed()
    console.log(await (await UsedCarPage.subHeading).getText())
    expect(await UsedCarPage.selectVehicle).toBeDisplayed()
    await (await UsedCarPage.selectVehicle).click()
    await UsedCarPage.selectVehicleFromDropdown()
    await (await UsedCarPage.nextBtn).click()
    await browser.pause('2000')
    await (await UsedCarPage.nextBtn).click()
    await browser.pause('2000')
    await (await UsedCarPage.nextBtn).click()


    expect(await UsedCarPage.lastStep).toBeDisplayed()
    expect(await UsedCarPage.doyouNeed).toBeDisplayed()
    console.log(await (await UsedCarPage.doyouNeed).getText())
    expect(await UsedCarPage.insurance).toBeDisplayed()
    console.log(await (await UsedCarPage.insurance).getText())
    expect(await UsedCarPage.loan).toBeDisplayed()
    console.log(await (await UsedCarPage.loan).getText())
    expect(await UsedCarPage.rcTransfer).toBeDisplayed()
    console.log(await (await UsedCarPage.rcTransfer).getText())
   expect(await UsedCarPage.roadAssistance).toBeDisplayed()
    console.log(await (await UsedCarPage.roadAssistance).getText())
    await (await UsedCarPage.loantoggle).click()
    await (await UsedCarPage.nextBtn).click()
    await browser.pause('2000')
    await (await UsedCarPage.nextBtn).click()
    await browser.pause('2000')
    expect(await UsedCarPage.submitheading).toBeDisplayed()
    await (await UsedCarPage.submitBtn).click()
    await (await UsedCarPage.submitViewMatch).click()
    await (await UsedCarPage.allrequirement).click()
    console.log("user able to select use car as per the Do you also need option")
  });


  it('TC_13 Verify user is able to select use car as per the How Quickly Do You Want to Buy? option', async () => {
    await base.androidLoginAsBuyer()
    await (await UsedCarPage.buy).click()
    await (await UsedCarPage.carimg).click() 
    await (await UsedCarPage.caroption).click()
    await (await UsedCarPage.searchLocation).click()
    await (await UsedCarPage.cityName).click()
    console.log("selected city")
    await (await UsedCarPage.nextBtn).click()
    expect(await UsedCarPage.subHeading).toBeDisplayed()
    console.log(await (await UsedCarPage.subHeading).getText())
    expect(await UsedCarPage.selectVehicle).toBeDisplayed()
    await (await UsedCarPage.selectVehicle).click()
    await UsedCarPage.selectVehicleFromDropdown()
    await (await UsedCarPage.nextBtn).click()
    await browser.pause('2000')
    await (await UsedCarPage.nextBtn).click()
    await browser.pause('2000')
    await (await UsedCarPage.nextBtn).click()

    expect(await UsedCarPage.lastStep).toBeDisplayed()
    expect(await UsedCarPage.quickBuy).toBeDisplayed()
    console.log(await (await UsedCarPage.quickBuy).getText())
    await (await UsedCarPage.weeks).click()
    console.log("selected 1-3 weeks")
    await (await UsedCarPage.nextBtn).click()
    await browser.pause('2000')
    await (await UsedCarPage.nextBtn).click()
    expect(await UsedCarPage.submitheading).toBeDisplayed()
    await (await UsedCarPage.submitBtn).click()
    await (await UsedCarPage.submitViewMatch).click()
    await (await UsedCarPage.allrequirement).click()
    console.log("user is able to select use car as per the How Quickly Do You Want to Buy? option")
  });

   it('TC_14 Verify user is able to select use car as per the Do You Wish to Exchange Your Vehicle option', async () => {
    await base.androidLoginAsBuyer()
    await (await UsedCarPage.buy).click()
    await (await UsedCarPage.carimg).click() 
    await (await UsedCarPage.caroption).click()
    await (await UsedCarPage.searchLocation).click()
    await (await UsedCarPage.cityName).click()
    console.log("selected city")
    await (await UsedCarPage.nextBtn).click()
    expect(await UsedCarPage.subHeading).toBeDisplayed()
    console.log(await (await UsedCarPage.subHeading).getText())
    expect(await UsedCarPage.selectVehicle).toBeDisplayed()
    await (await UsedCarPage.selectVehicle).click()
    await UsedCarPage.selectVehicleFromDropdown()
    await (await UsedCarPage.nextBtn).click()
    await browser.pause('2000')
    await (await UsedCarPage.nextBtn).click()
    await browser.pause('2000')

    await (await UsedCarPage.nextBtn).click()
    expect(await UsedCarPage.lastStep).toBeDisplayed()
    expect(await UsedCarPage.exchange).toBeDisplayed()
    console.log(await (await UsedCarPage.exchange).getText())
    await (await UsedCarPage.exchangetoggle).click()
    await (await UsedCarPage.nextBtn).click()
    await browser.pause('2000')
    await (await UsedCarPage.nextBtn).click()
    expect(await UsedCarPage.submitheading).toBeDisplayed()
    await (await UsedCarPage.submitBtn).click()
    await (await UsedCarPage.submitViewMatch).click()
    await (await UsedCarPage.allrequirement).click()
    console.log("Verified User is able to select used car as per the Do You Wish to Exchange Your Vehicle option") 
   
   });
 
  it('TC_15 Validation for match count while requirement creation and in requirement page', async () => {
    await base.androidLoginAsBuyer()
    await (await UsedCarPage.buy).click()
    await (await UsedCarPage.carimg).click() 
    await (await UsedCarPage.caroption).click()
    await (await UsedCarPage.searchLocation).click()
    await (await UsedCarPage.cityName).click()
    console.log("selected city")
    await (await UsedCarPage.nextBtn).click()
    expect(await UsedCarPage.subHeading).toBeDisplayed()
    console.log(await (await UsedCarPage.subHeading).getText())
    expect(await UsedCarPage.selectVehicle).toBeDisplayed()
    await (await UsedCarPage.selectVehicle).click()
    await UsedCarPage.selectVehicleFromDropdown()
    await (await UsedCarPage.nextBtn).click()
    await browser.pause('2000')
    await (await UsedCarPage.nextBtn).click()
    await browser.pause('2000')

    await (await UsedCarPage.nextBtn).click()
    await (await UsedCarPage.loantoggle).click()
    console.log("clicked on loan")
    await (await UsedCarPage.weeks).click()
    console.log("selected weeks")
    await (await UsedCarPage.nextBtn).click()
    await browser.pause('2000')
    await (await UsedCarPage.nextBtn).click()
    expect(await UsedCarPage.submitheading).toBeDisplayed()
    await (await UsedCarPage.submitBtn).click()
    expect(await UsedCarPage.almostdone).toBeDisplayed()
    console.log(await (await UsedCarPage.almostdone).getText())
    expect(await UsedCarPage.reqCount).toBeDisplayed()
    console.log(await (await UsedCarPage.reqCount).getText())
    console.log("user able to see Vehicle Match count ")
  });

});