const base = require("../../BaseClass/base");
const vehicleInsurancePage = require("../../Pages/Androidbrowser/vehicleInsurancePage");

describe('Check History', async () => {
    beforeEach(async () => {
        await driver.closeApp()
        await driver.launchApp()
    });
   it('TC_01 Verify the Functionality of Get Insurance', async () => {
        browser.url('/insurance')
        console.log("insurance page displayed")
        expect(await vehicleInsurancePage.vehicle_Information).toBeDisplayed()
        console.log("Vehicle Information displayed")
        expect(await vehicleInsurancePage.personal_Information).toBeDisplayed()
        console.log("Personal Information displayed")
        expect(await vehicleInsurancePage.insurance_Information).toBeDisplayed()
        console.log("Insurance Information displayed")
        await base.swipeUp()
        expect(await vehicleInsurancePage.car).toBeDisplayed()
        console.log("Car option displayed")
        expect(await vehicleInsurancePage.bike).toBeDisplayed()
        console.log("Bike option displayed")
        expect(await vehicleInsurancePage.scooter).toBeDisplayed()
        console.log("Scooter option displayed")
    });
    it('TC_02 Verify the process to Apply for Vehicle Insurance in 3 Easy Steps', async () => {
        //await vehicleInsurancePage.chromeConditions()
        browser.url('/insurance')
        console.log("insurance page displayed")
        expect(await vehicleInsurancePage.vehicle_Information).toBeDisplayed()
        console.log("Vehicle Information displayed")
        expect(await vehicleInsurancePage.personal_Information).toBeDisplayed()
        console.log("Personal Information displayed")
        expect(await vehicleInsurancePage.insurance_Information).toBeDisplayed()
        console.log("Insurance Information displayed")
    });
    it('TC_03 Verify Select vehicle Condition -Used functionality', async () => {
        //await vehicleInsurancePage.chromeConditions()
        browser.url('/insurance')
        console.log("insurance page displayed")
        expect(await vehicleInsurancePage.vehicle_Information).toBeDisplayed()
        console.log("Vehicle Information displayed")
        expect(await vehicleInsurancePage.personal_Information).toBeDisplayed()
        console.log("Personal Information displayed")
        expect(await vehicleInsurancePage.insurance_Information).toBeDisplayed()
        console.log("Insurance Information displayed")
        expect(await vehicleInsurancePage.used_condition).toBeDisplayed()
        console.log("Vehicle condition button Used is displayed")
        
    });
    it('TC_04 Verify "Select vehicle Condition -New " functionality', async () => {
        browser.url('/insurance')
        console.log("insurance page displayed")
        expect(await vehicleInsurancePage.vehicle_Information).toBeDisplayed()
        console.log("Vehicle Information displayed")
        expect(await vehicleInsurancePage.personal_Information).toBeDisplayed()
        console.log("Personal Information displayed")
        expect(await vehicleInsurancePage.insurance_Information).toBeDisplayed()
        console.log("Insurance Information displayed")
        expect(await vehicleInsurancePage.new_condition).toBeDisplayed()
        console.log("Vehicle condition button New is displayed")
        await (await vehicleInsurancePage.new_condition).click()
        console.log("New button Selected")
    });
    it('TC_05 Verify "Select From Dropdown" functionality.', async () => {
       browser.url('/insurance')
        console.log("insurance page displayed")
        expect(await vehicleInsurancePage.heading).toBeDisplayed()
        console.log(await (await vehicleInsurancePage.heading).getText())
        //await browser.pause(3000)
        expect(await vehicleInsurancePage.vehicle_Information).toBeDisplayed()
        console.log("Vehicle Information displayed")
        expect(await vehicleInsurancePage.personal_Information).toBeDisplayed()
        console.log("Personal Information displayed")
        expect(await vehicleInsurancePage.insurance_Information).toBeDisplayed()
        console.log("Insurance Information displayed")
        await base.swipeUp()
        expect(await vehicleInsurancePage.enterNo).toBeDisplayed()
         console.log("Enter Vehicle Registration Number shown")
        console.log("Vehicle Information Tab Dispalyed")
        await (await vehicleInsurancePage.enterNo).setValue("MH13Y4444")
        console.log("User entered Valid Registration Number")
        await browser.pause(5000)
        await (await vehicleInsurancePage.selectDropDown).waitForDisplayed()
        expect(await vehicleInsurancePage.selectDropDown).toBeDisplayed()
        await (await vehicleInsurancePage.selectDropDown).click()
        expect(await vehicleInsurancePage.make).toBeDisplayed()
        expect(await vehicleInsurancePage.model).toBeDisplayed()
        expect(await vehicleInsurancePage.yaer).toBeDisplayed()
        expect(await vehicleInsurancePage.trim).toBeDisplayed()
    });
    it('TC_06 Verify "Select Make" functionality of Select From Dropdown option', async () => {
        browser.url('/insurance')
        console.log("insurance page displayed")
        expect(await vehicleInsurancePage.heading).toBeDisplayed()
        console.log(await (await vehicleInsurancePage.heading).getText())
        //await browser.pause(3000)
        expect(await vehicleInsurancePage.vehicle_Information).toBeDisplayed()
        console.log("Vehicle Information displayed")
        expect(await vehicleInsurancePage.personal_Information).toBeDisplayed()
        console.log("Personal Information displayed")
        expect(await vehicleInsurancePage.insurance_Information).toBeDisplayed()
        console.log("Insurance Information displayed")
        await base.swipeUp()
        expect(await vehicleInsurancePage.enterNo).toBeDisplayed()
         console.log("Enter Vehicle Registration Number shown")
        console.log("Vehicle Information Tab Dispalyed")
        await (await vehicleInsurancePage.enterNo).setValue("MH13Y4444")
        console.log("User entered Valid Registration Number")
        await browser.pause(5000)
        await (await vehicleInsurancePage.selectDropDown).waitForDisplayed()
        expect(await vehicleInsurancePage.selectDropDown).toBeDisplayed()
        await (await vehicleInsurancePage.selectDropDown).click()
        await base.switchToWebview()
        await (await vehicleInsurancePage.makeDropDown).click()
         await base.switchToNativeApp()
        console.log("Clicked on Make Drop down to select Make of Expected vehicle")
    });
     it("TC_07 Verify Select Model functionality of Select From Dropdown option", async () => {
       browser.url('/insurance')
        console.log("insurance page displayed")
        expect(await vehicleInsurancePage.heading).toBeDisplayed()
        console.log(await (await vehicleInsurancePage.heading).getText())
        //await browser.pause(3000)
        expect(await vehicleInsurancePage.vehicle_Information).toBeDisplayed()
        console.log("Vehicle Information displayed")
        expect(await vehicleInsurancePage.personal_Information).toBeDisplayed()
        console.log("Personal Information displayed")
        expect(await vehicleInsurancePage.insurance_Information).toBeDisplayed()
        console.log("Insurance Information displayed")
        await base.swipeUp()
        expect(await vehicleInsurancePage.enterNo).toBeDisplayed()
         console.log("Enter Vehicle Registration Number shown")
        console.log("Vehicle Information Tab Dispalyed")
        await (await vehicleInsurancePage.enterNo).setValue("MH13Y4444")
        console.log("User entered Valid Registration Number")
        await browser.pause(5000)
        await (await vehicleInsurancePage.selectDropDown).waitForDisplayed()
        expect(await vehicleInsurancePage.selectDropDown).toBeDisplayed()
        await (await vehicleInsurancePage.selectDropDown).click()
        await base.switchToWebview()
        await (await vehicleInsurancePage.modelDropdown).click()
         await base.switchToNativeApp()
        console.log("Model Drop Down id displayed")
   });

   it("TC_08 Verify Select Year Functionality Of Select From Dropdown Option", async () => {
        browser.url('/insurance')
        console.log("insurance page displayed")
        expect(await vehicleInsurancePage.heading).toBeDisplayed()
        console.log(await (await vehicleInsurancePage.heading).getText())
        //await browser.pause(3000)
        expect(await vehicleInsurancePage.vehicle_Information).toBeDisplayed()
        console.log("Vehicle Information displayed")
        expect(await vehicleInsurancePage.personal_Information).toBeDisplayed()
        console.log("Personal Information displayed")
        expect(await vehicleInsurancePage.insurance_Information).toBeDisplayed()
        console.log("Insurance Information displayed")
        await base.swipeUp()
        expect(await vehicleInsurancePage.enterNo).toBeDisplayed()
         console.log("Enter Vehicle Registration Number shown")
        console.log("Vehicle Information Tab Dispalyed")
        await (await vehicleInsurancePage.enterNo).setValue("MH13Y4444")
        console.log("User entered Valid Registration Number")
        await browser.pause(5000)
        await (await vehicleInsurancePage.selectDropDown).waitForDisplayed()
        expect(await vehicleInsurancePage.selectDropDown).toBeDisplayed()
        await (await vehicleInsurancePage.selectDropDown).click()
        await base.switchToWebview()
        await (await vehicleInsurancePage.yearDropdown).waitForDisplayed()
        expect(await vehicleInsurancePage.yearDropdown).toBeDisplayed()
        await (await vehicleInsurancePage.yearDropdown).click()
       await base.switchToNativeApp()
       console.log("Year Drop Down is displayed")
});
it("TC_09 Verify Select Trim Functionality Of Select From Dropdown option", async () => {
        browser.url('/insurance')
        console.log("insurance page displayed")
        expect(await vehicleInsurancePage.heading).toBeDisplayed()
        console.log(await (await vehicleInsurancePage.heading).getText())
        //await browser.pause(3000)
        expect(await vehicleInsurancePage.vehicle_Information).toBeDisplayed()
        console.log("Vehicle Information displayed")
        expect(await vehicleInsurancePage.personal_Information).toBeDisplayed()
        console.log("Personal Information displayed")
        expect(await vehicleInsurancePage.insurance_Information).toBeDisplayed()
        console.log("Insurance Information displayed")
        await base.swipeUp()
        expect(await vehicleInsurancePage.enterNo).toBeDisplayed()
         console.log("Enter Vehicle Registration Number shown")
        console.log("Vehicle Information Tab Dispalyed")
        await (await vehicleInsurancePage.enterNo).setValue("MH13Y4444")
        console.log("User entered Valid Registration Number")
        await browser.pause(5000)
        await (await vehicleInsurancePage.selectDropDown).waitForDisplayed()
        expect(await vehicleInsurancePage.selectDropDown).toBeDisplayed()
        await (await vehicleInsurancePage.selectDropDown).click()
        await base.switchToWebview()
        await (await vehicleInsurancePage.trimDropDown).waitForDisplayed()
       expect(await vehicleInsurancePage.trimDropDown).toBeDisplayed()
       await (await vehicleInsurancePage.trimDropDown).click()
       await base.switchToNativeApp()
        console.log("Trim Drop Down id displayed")
});
it("TC_10 Verify the Back Button Functionality on Personal Information page of Insurance", async () => {
         browser.url('/insurance')
        console.log("insurance page displayed")
        expect(await vehicleInsurancePage.heading).toBeDisplayed()
        console.log(await (await vehicleInsurancePage.heading).getText())
        expect(await vehicleInsurancePage.vehicle_Information).toBeDisplayed()
        console.log("Vehicle Information Tab Dispalyed")
        await (await vehicleInsurancePage.used_condition).click()
        await (await vehicleInsurancePage.car).click()
         expect(await vehicleInsurancePage.enterNo).toBeDisplayed()
         console.log("Enter Vehicle Registration Number shown")
        console.log("Vehicle Information Tab Dispalyed")
        await (await vehicleInsurancePage.enterNo).setValue("MH13Y4444")
        console.log("User entered Valid Registration Number")
        await (await vehicleInsurancePage.vehicleDetails).setValue("Tata Indigo LS 2003")
        await (await vehicleInsurancePage.pickModel).click()
        console.log("User select Vehicle Model")
        await (await vehicleInsurancePage.nextBtn).waitForDisplayed({ timeout: 5000 })
        await (await vehicleInsurancePage.nextBtn).click()
        console.log("User Click On next Button")
        expect(await vehicleInsurancePage.name).toBeDisplayed()
        console.log("Name displayed on Personal Information")
        expect(await vehicleInsurancePage.email).toBeDisplayed()
        console.log("EmailID displayed on Personal Information")
        expect(await vehicleInsurancePage.Number).toBeDisplayed()
        console.log("Contact Number displayed on Personal Information")
        expect(await vehicleInsurancePage.BackBtn1).toBeDisplayed()
        console.log("Back Button Shown on Vehicle Information Page")
        await (await vehicleInsurancePage.BackBtn1).click()
        await (await vehicleInsurancePage.selectCondition).waitForDisplayed({ timeout: 5000 })
        expect(await vehicleInsurancePage.selectCondition).toBeDisplayed()
        console.log("After ckick on Back Button user able to navigate to Pravious Page")
    });
    it("TC_11 Verify the Next Button Functionality on Personal Information page of Insurance", async () => {
        browser.url('/insurance')
        console.log("insurance page displayed")
        expect(await vehicleInsurancePage.heading).toBeDisplayed()
        console.log(await (await vehicleInsurancePage.heading).getText())
        expect(await vehicleInsurancePage.selectCondition).toBeDisplayed()
        await base.swipeUp()
        await (await vehicleInsurancePage.car).click()
        await (await vehicleInsurancePage.enterNo).setValue("MH13Y4444")
        console.log("User entered Valid Registration Number")
        await (await vehicleInsurancePage.vehicleDetails).setValue("Tata Indigo LS 2003")
        await (await vehicleInsurancePage.pickModel).click()
        console.log("User select Vehicle Model")
        await (await vehicleInsurancePage.nextBtn).click()
        console.log("User Click On next Button")
        await base.switchToWebview()
        console.log(await (await vehicleInsurancePage.name).getText())
        await base.switchToNativeApp()
        console.log("Name shown")
        await base.switchToWebview()
        console.log(await (await vehicleInsurancePage.email).getText())
        await base.switchToNativeApp()
        console.log("Mail ID shown ")
        await base.switchToWebview()
        console.log(await (await vehicleInsurancePage.phone).getText())
        await base.switchToNativeApp()
        console.log("Phone shown on Personal Details Page")
        await base.switchToWebview()
        expect(await vehicleInsurancePage.BackBtn1).toBeDisplayed()
         await base.switchToNativeApp()
        console.log("Back Button is shown")
         await base.switchToWebview()
        expect(await vehicleInsurancePage.nextBtn2).toBeDisplayed()
        awaiy(await vehicleInsurancePage.nextBtn2).click()
        await base.switchToNativeApp()
         expect(await vehicleInsurancePage.phnVerificationPage).toBeDisplayed()
        console.log("After click on Next button Phone Number Verification page get displayed")
    });
    it("TC_12 Verify the fields on Personal Information", async () => {
       browser.url('/insurance')
        console.log("insurance page displayed")
        expect(await vehicleInsurancePage.heading).toBeDisplayed()
        console.log(await (await vehicleInsurancePage.heading).getText())
        expect(await vehicleInsurancePage.selectCondition).toBeDisplayed()
        await base.swipeUp()
        await (await vehicleInsurancePage.car).click()
        await (await vehicleInsurancePage.enterNo).setValue("MH13Y4444")
        console.log("User entered Valid Registration Number")
        await (await vehicleInsurancePage.vehicleDetails).setValue("Tata Indigo LS 2003")
        await (await vehicleInsurancePage.pickModel).click()
        console.log("User select Vehicle Model")
        await (await vehicleInsurancePage.nextBtn).click()
        console.log("User Click On next Button")
        await base.switchToWebview()
        console.log(await (await vehicleInsurancePage.name).getText())
        await base.switchToNativeApp()
        console.log("Name shown")
        await base.switchToWebview()
        console.log(await (await vehicleInsurancePage.email).getText())
        await base.switchToNativeApp()
        console.log("Mail ID shown ")
        await base.switchToWebview()
        console.log(await (await vehicleInsurancePage.phone).getText())
        await base.switchToNativeApp()
        console.log("Phone shown on Personal Details Page")
        await base.switchToWebview()
        expect(await vehicleInsurancePage.BackBtn1).toBeDisplayed()
         await base.switchToNativeApp()
        console.log("Back Button is shown")
         await base.switchToWebview()
        expect(await vehicleInsurancePage.nextBtn2).toBeDisplayed()
        await base.switchToNativeApp()
        console.log("Next button is Shown")
    });
    it("TC_13 Verify the functionality of Select a vehicle Type", async () => {
       browser.url('/insurance')
        console.log("insurance page displayed")
        expect(await vehicleInsurancePage.heading).toBeDisplayed()
        console.log(await (await vehicleInsurancePage.heading).getText())
        expect(await vehicleInsurancePage.selectCondition).toBeDisplayed()
        await base.swipeUp()
        console.log("Select vehicle type Heading shown for Used and New")
        expect(await vehicleInsurancePage.used_condition).toBeDisplayed()
        console.log("Used Vehicle Condition is displayed")
        expect(await vehicleInsurancePage.new_condition).toBeDisplayed()
        console.log("New Vehicle Condition is displayed")
        expect(await vehicleInsurancePage.selectType).toBeDisplayed()
        console.log("Vehicle Types Displayed")
        expect (await vehicleInsurancePage.car).toBeDisplayed()
        console.log("Car type of vehicle shown")
        expect(await vehicleInsurancePage.bike).toBeDisplayed()
        console.log("Bike is Displayed");
        expect(await vehicleInsurancePage.scooter).toBeDisplayed()
        console.log("Scooter is Displayed");
    
});
});