
describe('Used Car', async () => {
    it('Verify car option is the display with used Condition to the buyer', async () => {
        const popUp = await $('(//button[@class="close em-show-later"])[2]')
        popUp.waitForDisplayed()
        popUp.click()
        await (await $('#user_details').moveTo())
        const input = $('//a[text()="Log In"]')
        input.click();
        await $('#userLogin').setValue("vikasy898@gmail.com")
        const clickOnEmail = await $('//li[@class="active login-vai"]')
        clickOnEmail.click();
        await $('#password').setValue("Vtest@123")
        const EnterPAss = await $('//input[@value="Login"]')
        EnterPAss.click();
        console.log('User Successfully login to application with valid credentials')
        await $('//span[text()="Submit "]').click()
        console.log('User click on submit requirements ')
        await $('(//span[@class="s-MuiButton-label"])[1]').click()
        console.log('Select Car from option ')
        await $('//span[text()="Used"]').click()
        console.log('select used car condition ')
        const car = await $('//span[text()="Car"]')
        expect(car).toBeDisplayed()
        const bike = await $('//span[text()="Bike"]')
        expect(bike).toBeDisplayed()
        const scooter = await $('//span[text()="Scooter"]')
        expect(scooter).toBeDisplayed()
        const newButton = await $('(//span[text()="New"])[2]')
        expect(newButton).toBeDisplayed()
        const used = await $('//span[text()="Used"]')
        expect(used).toBeDisplayed()
        const usedButton = await $('(//input[@class="s-s42"])[2]')
        console.log(await usedButton.isSelected())
        const newRButton = await $('(//input[@class="s-s42"])[1]')
        console.log(await newRButton.isSelected())
        const location = await $('//p[text()="Location"]')
        expect(location).toBeDisplayed()
        const currentLocation = await $('//div[text()="Current Location"]')
        expect(currentLocation).toBeDisplayed()
        const nextButton = await $('//span[text()="Next "]')
        expect(nextButton).toBeDisplayed()

    });
    it('Verify error message without entering location', async () => {
        const nextButton = await $('//span[text()="Next "]')
        await $('//span[text()="Used"]').click()
        nextButton.click()
        const errorMsg = await $('//p[text()="Please Select The City"]')
        await errorMsg.waitForExist({ timeout: 5000 })
        expect(await errorMsg.getText())
        console.log('Error message Displayed')

    });

    it('Verify user able to select location using location option', async () => {
        const currentLocation = await $('//div[text()="Current Location"]')
        currentLocation.click()
        const msg = await $('//div[text()="Current Location"]')
        await msg.waitForExist({ timeout: 3000 })
        expect(await msg.getText())
        console.log('User Selected Current location')


    });

    it('Verify user able to select car model from Entering your vehicle details as per requirement', async () => {
        const nextButton = await $('//span[text()="Next "]')
        const newButton = await $('(//span[text()="New"])[2]')
        newButton.click();
        await $('//span[text()="Used"]').click()
        nextButton.click();
        const msg = await $('//label[text()="Enter Your Vehicle Details"]')
        await msg.waitForExist({ timeout: 5000 })
        console.log('User entered Vehicle Details ')
        await $('//input[@placeholder="E.g Maruti Suzuki Swift 2017 LDI"]').setValue("swift")
        await $('(//li[@class="d-block d-margin-bottom-10 d-font-size-13"])[1]').click()
        console.log('User selected vehicle as per the requirement ')
        const carName = await $('//span[@class="s-MuiChip-label"]')
        expect(carName).toBeDisplayed()
        const addBtn = await $('//p[text()=" Add Another Vehicle"]')
        expect(addBtn).toBeDisplayed()
    });
    it('Verify user able to select car model through select from the dropdown as per requirement', async () => {
        await $('//div[@role="button"]//*[local-name()="svg"]').click()
        await $('//span[text()="Select From"]').click()
        console.log('clicked on select from dropDown')
        const orSearch = await $('//span[text()="Or Search"]')
        await orSearch.waitForExist({ timeout: 2000 })
        const nextButton = await $('//span[text()="Next "]')
        nextButton.click();
        const errorMsg = await $('//p[text()="Please select the Vehicles"]')
        await errorMsg.waitForExist({ timeout: 3000 })
        await $('//select[@class="form-control floating-control pmmyt-make-f"]').click()
        console.log('Clicked on select make')
        await $('//option[text()="BMW"]').click()
        console.log('selected BWM from list')
        await $('//select[@name="model"]').click()
        console.log('Clicked on select model')
        await $('//option[text()="1 Series"]').click()
        console.log('selected 1 series model')
        nextButton.click()
        const carName = await $('//span[@class="s-MuiChip-label"]')
        expect(carName).toBeDisplayed()
        const addBtn = await $('//p[text()=" Add Another Vehicle"]')
        expect(addBtn).toBeDisplayed()





    });
    it('Verify user able to select car model through Let Droom Suggest for you as per requirement', async () => {
        const orSearch = await $('//h5[text()="Now Share Your Dream Vehicle Basic Details"]')
        await orSearch.waitForExist({ timeout: 20000 })
        await $('//button[@class="s-MuiButtonBase-root s-MuiIconButton-root"]//span[@class="s-MuiIconButton-label"]//*[local-name()="svg"]').click()
        const carName = await $('//span[@class="s-MuiChip-label"]')
        expect(carName).toBeDisplayed()
        await $('(//div[@role="button"]//*[local-name()="svg"])[1]').click()
        await $('//button[text()="Let Droom Suggest for you"]').click()
        const msg = await $('//h5[text()="Let us know what you are looking for"]')
        await msg.waitForExist({ timeout: 20000 })
        const budget = await $('//p[text()="What is Your Budget?"]')
        expect(budget).toBeDisplayed()
        const bodyType = await $('//p[text()="Body Type"]')
        expect(bodyType).toBeDisplayed()
        const age = await $('//p[text()="Age of Vehicle"]')
        expect(age).toBeDisplayed()
        const more = await $('//p[text()="Add More Detail "]')
        expect(more).toBeDisplayed()


    });
    it('Verify user able to select use car as per the Fuel type', async () => {
        await $('//*[name()="path" and contains(@d,"M20 11H7.8")]').click()
        const msg = await $('//label[text()="Enter Your Vehicle Details"]')
        await msg.waitForExist({ timeout: 20000 })
        console.log('User entered Vehicle Details ')
        await $('//span[text()="Select From"]').click()
        console.log('Clicked on select make')
        await $('//option[text()="BMW"]').click()
        console.log('selected BWM from list')
        await $('//select[@name="model"]').click()
        console.log('Clicked on select model')
        await $('//option[text()="1 Series"]').click()
        console.log('selected 1 series model')
        await $('//select[@class="form-control floating-control pmmyt-year-f"]').click()
        await $('//option[text()="2018"]').click()
        console.log('selected year 2018')
        await $('//select[@class="form-control floating-control pmmyt-trim-f"]').click()
        await $('//option[text()="118D SPORT LINE"]').click()
        console.log('selected trim 118D SPORT LINE')
        const nextButton = await $('//span[text()="Next "]')
        nextButton.click()
        const basicDetails = await $('//h5[text()="Now Share Your Dream Vehicle Basic Details"]')
        await basicDetails.waitForExist({ timeout: 10000 })
        const budget = await $('//p[text()="What is Your Budget?"]')
        expect(budget).toBeDisplayed()
        const fuelType = await $('//p[text()="Fuel Type"]')
        expect(fuelType).toBeDisplayed()
        const petrol = await $('(//span[@class="s-MuiIconButton-label"])[3]')
        petrol.click()
        petrol.isSelected()
        nextButton.click()
        await browser.pause(2000)
        nextButton.click()
        const done = await $('//h5[text()="You are Almost Done!"]')
        expect(done).toBeDisplayed()
        await $('//span[text()="Submit & View All Matches "]').click()
        const requirements = await $('//span[text()=" View all Requirements "]')
        await requirements.waitForExist({ timeout: 10000 })
        requirements.click()
        const newRequirements = await $('//span[text()=" + Add New Requirement"]')
        await newRequirements.waitForExist({ timeout: 10000 })


    });
    it('Verify user able to select use car as per the Exterior Color', async () => {
        await browser.pause(2000)
        await $('//i[@class="web-g-icon web-g-icon-my-requirement d-font-size-22 d-display-inline-block d-position-relative d-valign-middle"]').click()
        console.log('User click on submit requirements ')
        await $('(//span[@class="s-MuiButton-label"])[1]').click()
        console.log('Select Car from option ')
        await $('//span[text()="Used"]').click()
        console.log('select used car condition ')
        const currentLocation = await $('//div[text()="Current Location"]')
        currentLocation.click()
        await browser.pause(2000)
        const nextButton = await $('//span[text()="Next "]')
        nextButton.click()
        const msg = await $('//label[text()="Enter Your Vehicle Details"]')
        await msg.waitForExist({ timeout: 5000 })
        console.log('User entered Vehicle Details ')
        await $('//input[@placeholder="E.g Maruti Suzuki Swift 2017 LDI"]').setValue("swift")
        await $('(//li[@class="d-block d-margin-bottom-10 d-font-size-13"])[1]').click()
        console.log('User selected vehicle as per the requirement ')
        nextButton.click()
        const basicDetails = await $('//h5[text()="Now Share Your Dream Vehicle Basic Details"]')
        await basicDetails.waitForExist({ timeout: 20000 })
        const redColor = await $('//input[@value="red"]').click()
        nextButton.click()
        await browser.pause(2000)
        nextButton.click()
        await $('//span[text()="Submit & View All Matches "]').click()
        const requirements = await $('//span[text()=" View all Requirements "]')
        await requirements.waitForExist({ timeout: 20000 })
        requirements.click()
        const newRequirements = await $('//span[text()=" + Add New Requirement"]')
        await newRequirements.waitForExist({ timeout: 20000 })

    });
    it('Verify user able to select use car as per the Transmission Type', async () => {
        await browser.pause(2000)
        await $('//i[@class="web-g-icon web-g-icon-my-requirement d-font-size-22 d-display-inline-block d-position-relative d-valign-middle"]').click()
        console.log('User click on submit requirements ')
        await $('(//span[@class="s-MuiButton-label"])[1]').click()
        console.log('Select Car from option ')
        await $('//span[text()="Used"]').click()
        console.log('select used car condition ')
        const currentLocation = await $('//div[text()="Current Location"]')
        currentLocation.click()
        await browser.pause(2000)
        const nextButton = await $('//span[text()="Next "]')
        nextButton.click()
        const msg = await $('//label[text()="Enter Your Vehicle Details"]')
        await msg.waitForExist({ timeout: 20000 })
        await $('//span[text()="Select From"]').click()
        console.log('Clicked on select make')
        await $('//option[text()="BMW"]').click()
        console.log('selected BWM from list')
        await $('//select[@name="model"]').click()
        console.log('Clicked on select model')
        await $('//option[text()="1 Series"]').click()
        console.log('selected 1 series model')
        await $('//select[@class="form-control floating-control pmmyt-year-f"]').click()
        await $('//option[text()="2018"]').click()
        console.log('selected year 2018')
        await $('//select[@class="form-control floating-control pmmyt-trim-f"]').click()
        await $('//option[text()="118D SPORT LINE"]').click()
        console.log('selected trim 118D SPORT LINE')
        nextButton.click()
        const basicDetails = await $('//h5[text()="Now Share Your Dream Vehicle Basic Details"]')
        await basicDetails.waitForExist({ timeout: 20000 })
        await $('//input[@value="red"]').click()
        await $('//img[@alt="Automatic"]').click()
        nextButton.click()
        await browser.pause(2000)
        nextButton.click()
        await $('//span[text()="Submit & View All Matches "]').click()
        const requirements = await $('//span[text()=" View all Requirements "]')
        await requirements.waitForExist({ timeout: 20000 })
        requirements.click()
        const newRequirements = await $('//span[text()=" + Add New Requirement"]')
        await newRequirements.waitForExist({ timeout: 20000 })

    });
    it('Verify user able to select use car as per the Do you also need option', async () => {
        

    });

});