const Base = require('../../BaseClass/base')
const ecoPage = require('../../Pages/Android/ECOInspectionPage')
describe('ECOInspection', () => {
    beforeEach(async () => {
        await driver.closeApp()
        await driver.launchApp()
    });
  it('TC_01 Verify the Functionaliy of Buyer on ECO', async () => {
        await (await ecoPage.mainPopup).isDisplayed()
        await (await ecoPage.mainPopup).click()
        console.log('Application Launched')
        await  ecoPage.traverseToECO()
        await (await ecoPage.Buyer).isDisplayed()
        console.log("Buyer is availbale on ECO page")
        await (await ecoPage.Seller).isDisplayed()
        console.log("Seller is availbale on ECO page")
        await (await ecoPage.Technician).isDisplayed()
        console.log("Technician is availbale on ECO page")
        await (await ecoPage.Check_Repair_Estimate).isDisplayed()
        console.log("Check Repair Estimate is displayed")
        await(await ecoPage.Check_Repair_Estimate).click()
        await(await ecoPage.make).waitForClickable({ timeout: 3000 })
        await(await ecoPage.make).click()
        await(await ecoPage.MakeName).click()
        await(await ecoPage.model).click()
        await(await ecoPage.ModelName).click()
        await(await ecoPage.Trim).click()
        await(await ecoPage.TrimTo).click()
        await(await ecoPage.location).click()
        await(await ecoPage.location).setValue("Delhi")
        await(await ecoPage.delhi).click()
        await(await ecoPage..Next).click()
        expect(await ecoPage.repairServiceHeading).isDisplayed()
        console.log("Heading is displayed as : "+await(await ecoPage.repairServiceHeading ).getText())
        await(await ecoPage.airFilter).click()
        base.swipeUp()
        await(await ecoPage.getEstimate).click()
        expect(await ecoPage.Estimated_RepairCost).isDisplayed()
        console.log(await(await ecoPage.Estimated_RepairCost ).getText())
    }); 
    it('TC_04 Verify Features on ECO for Four Wheelers', async () => {
        await browser.back()
        await ecoPage.traverseToECO()
        await (await ecoPage.Seller).click()
        expect(ecoPage.RegiAsVendor).toBeDisplayed()
        console.log("Register As a Vendor is Displayed")
        await (await ecoPage.RegiAsVendor).waitForEnabled({ timeout: 30000 })
        await (await ecoPage.RegiAsVendor).click()
        console.log("Clicked on Resister as Vendor")
        expect(await ecoPage.features).toBeDisplayed()
        console.log("After click on Check Repair Estimate Feature tab is shown")
        await(await ecoPage.hamburgerMenuECO).click()
        await (await ecoPage.features).waitForClickable({timeout:1500})
        await (await ecoPage.features).click()
        expect(await ecoPage.features_FourWheelers).toBeDisplayed()
        console.log("ECO inspection Page is Displayed for Four wheelers")
        expect(await ecoPage.chechPoint_FourWheeler).toBeDisplayed()
        console.log("checkpoint for four wheelers are displayed")
        expect(await ecoPage.assessment).toBeDisplayed()
        console.log(await (ecoPage.assessment).getText())
        console.log("Inspection Checkpoints for Four Wheeler Displayed");
    });
    it('TC_05 Verify Features on ECO for Two Wheelers', async () => {
        expect(await ecoPage.featurs_TwoWheelers).toBeDisplayed()
        await(await ecoPage.featurs_TwoWheelers).click()
        console.log("Clicked on Two Wheelers");
        expect(await ecoPage.chechPoint_TwoWheeler).toBeDisplayed()
        console.log(await (await ecoPage.chechPoint_TwoWheeler).getText())
        console.log("Check Points for Two Wheeler displayed")
        expect(await ecoPage.tires_Wheels).toBeDisplayed()
        console.log(await (await ecoPage.tires_Wheels).getText())
    });
});