const Base = require('../../BaseClass/base');
const { ECO } = require('../../Pages/Web/ECO_InspectionPage');
const ECO_InspectionPage = require('../../Pages/Web/ECO_InspectionPage')
describe('ECO Inspection', () => {
    it('TC_01 Verify the Functionaliy of Buyer on ECO', async () => {
        await ECO_InspectionPage.traverseToECO()
        expect(await ECO_InspectionPage.Seller).toBeDisplayed()
        console.log("Seller option is availbale on page")
        expect(await ECO_InspectionPage.Buyer).toBeDisplayed()
        console.log("Buyer option is availbale on page")
        expect(await ECO_InspectionPage.Technician).toBeDisplayed()
        console.log("Technician option is shown on the page")
        await (await ECO_InspectionPage.Buyer).click()
        console.log("Clicked on Buyer")
        expect(await ECO_InspectionPage.Check_Repair_Estimate).toBeDisplayed()
        console.log("Repair Estimate option is shown")
        expect(await ECO_InspectionPage.BookInspection).toBeDisplayed()
        console.log("Book Inspection option is shown")
        await (await ECO_InspectionPage.Check_Repair_Estimate).waitForEnabled({ timeout: 1500 })
        await (await ECO_InspectionPage.Check_Repair_Estimate).click()
        expect(await ECO_InspectionPage.Repair_EstimateHeading).toBeDisplayed()
        console.log("Select Car to Check Estimated Repair Cost is displayed as a heading")
        console.log(await (await ECO_InspectionPage.Repair_EstimateHeading).getText())
        expect(await ECO_InspectionPage.getEstimate).toBeDisplayed()
        console.log("After click on Next button Get Estimate Button is shown")
        expect(await ECO_InspectionPage.break_Repair).toBeDisplayed()
        console.log("Break Reparing Option is Shown")
        expect(await ECO_InspectionPage.electrical_Repair).toBeDisplayed()
        console.log("Electical Reapring Option is Shown")
        expect(await ECO_InspectionPage.AC_Repair).toBeDisplayed()
        console.log("AC repairing Option is Shown")
        expect(await ECO_InspectionPage.wheel_Repair).toBeDisplayed()
        console.log("Wheels Repairing Option is Shown")
        expect(await ECO_InspectionPage.front_Brake).toBeDisplayed()
        console.log("Services are shown for every category of repair")
        await (await ECO_InspectionPage.front_Brake).click()
        expect(await ECO_InspectionPage.getEstimate).toBeDisplayed()
        console.log("Get Estimate Button shown after filling all the required Details")
        await (await ECO_InspectionPage.getEstimate).click()
        expect(await ECO_InspectionPage.Estimated_RepairCost).toBeDisplayed()
        console.log(await (await ECO_InspectionPage.Estimated_RepairCost).getText())
    });
    it('TC_04 Verify Features on ECO for Four Wheelers', async () => {
        await ECO_InspectionPage.traverseToECO()
        expect(ECO_InspectionPage.Check_Repair_Estimate).toBeDisplayed()
        console.log("Check Repair Estimate is Displayed")
        await (await ECO_InspectionPage.Check_Repair_Estimate).click()
        console.log("Clicked on Check Repair Estimate")
        expect(await ECO_InspectionPage.features).toBeDisplayed()
        console.log("After click on Check Repair Estimate Feature tab is shown")
        await (await ECO_InspectionPage.features).click()
        expect(await ECO_InspectionPage.features_FourWheelers).toBeDisplayed()
        console.log("ECO inspection Page is Displayed for Four wheelers")
        expect(await ECO_InspectionPage.chechPoint_FourWheeler).toBeDisplayed()
        console.log("checkpoint for fi=our wheelers are displayed")
        expect(await ECO_InspectionPage.assessment).toBeDisplayed()
    });
    it('TC_05 Verify Features on ECO for Two Wheelers', async () => {
        await ECO_InspectionPage.traverseToECO()
        expect(await ECO_InspectionPage.Check_Repair_Estimate).toBeDisplayed()
        console.log("Check Repair Estimate is Displayed")
        await (await ECO_InspectionPage.Check_Repair_Estimate).click()
        expect(await ECO_InspectionPage.features).toBeDisplayed()
        console.log("After click on Check Repair Estimate Feature tab is shown")
        await (await ECO_InspectionPage.features).click()
        expect(await ECO_InspectionPage.featurs_TwoWheelers).toBeDisplayed()
        expect(await ECO_InspectionPage.chechPoint_TwoWheeler).toBeDisplayed()
        expect(await ECO_InspectionPage.tires_Wheels).toBeDisplayed()
    })
    it('TC_06 Verify Car Inspection  Service on Eco', async () => {
        await ECO_InspectionPage.traverseToECO()
        expect(await ECO_InspectionPage.ECO_Offering).toBeDisplayed()
        console.log("ECO Offering Heading displayed for Cars and the Bikes")
        expect(await ECO_InspectionPage.cars_OnECO_Offering).toBeDisplayed()
        console.log("Cars option available under ECO offering")
        console.log(await (await ECO_InspectionPage.cars_OnECO_Offering).getText())
        expect(await ECO_InspectionPage.inspection_Services).toBeDisplayed()
        console.log("Inspection services displayed under ECO Offering")
        expect(await ECO_InspectionPage.basic_Insection).toBeDisplayed()
        console.log("Basic inspection is shown")
        console.log(await (await ECO_InspectionPage.amount_basic).getText())
        expect(await ECO_InspectionPage.premium_Inspection).toBeDisplayed()
        console.log("Premium inspection is Shown")
        console.log(await (await ECO_InspectionPage.amount_premium).getText())
        expect(await ECO_InspectionPage.premium_Plus_Inspection).toBeDisplayed()
        console.log("Premium plus Inspection shown")
        console.log(await (await ECO_InspectionPage.amount_primiumPlus_Inspection).getText())
        expect(await ECO_InspectionPage.basic_Report).toBeDisplayed()
        console.log("Link to Download Basic report is displayed")
        expect(await ECO_InspectionPage.premium_Report).toBeDisplayed()
        console.log("Link to Download Premium report is displayed")
        expect(await ECO_InspectionPage.premiumPlus_InspectionReport).toBeDisplayed()
        console.log("Link to Download Premium plus Inspection report is displayed")
    });
    it('TC_07 Verify Bike Inspection  Service on ECO', async () => {
        await ECO_InspectionPage.traverseToECO()
        expect(await ECO_InspectionPage.ECO_Offering).toBeDisplayed()
        console.log("ECO Offering Heading displayed for Cars and the Bikes")
        expect(await ECO_InspectionPage.bikes_OnECO_Offering_OnECO_Offering).toBeDisplayed()
        console.log("Bikes option available under ECO offering")
        expect(await ECO_InspectionPage.inspection_Services).toBeDisplayed()
        console.log("Inspection services displayed under ECO Offering")
        expect(await ECO_InspectionPage.basic_Insection).toBeDisplayed()
        console.log("Basic inspection is shown")
        console.log(await (await ECO_InspectionPage.amount_basic).getText())
        expect(await ECO_InspectionPage.premium_Inspection).toBeDisplayed()
        console.log("Premium inspection is Shown")
        console.log(await (await ECO_InspectionPage.amount_premium).getText())
        expect(await ECO_InspectionPage.premium_Plus_Inspection).toBeDisplayed()
        console.log("Premium plus Inspection shown")
        console.log(await (await ECO_InspectionPage.amount_primiumPlus_Inspection).getText())
        expect(await ECO_InspectionPage.basic_Report).toBeDisplayed()
        console.log("Link to Download Basic report is displayed")
        expect(await ECO_InspectionPage.premium_Report).toBeDisplayed()
        console.log("Link to Download Premium report is displayed")
        expect(await ECO_InspectionPage.premiumPlus_InspectionReport).toBeDisplayed()
        console.log("Link to Download Premium plus Inspection report is displayed")
    });
    it('TC_08 Verify scooter Inspection Service on ECO', async () => {
        await ECO_InspectionPage.traverseToECO()
        expect(ECO_InspectionPage.Check_Repair_Estimate).toBeDisplayed()
        console.log("Check Repair Estimate is Displayed")
        await (ECO_InspectionPage.Check_Repair_Estimate).click()
        expect(ECO_InspectionPage.Services).toBeDisplayed()
        console.log("After click on Check Repair Estimate Services tab is shown")
        expect(ECO_InspectionPage.Services).toBeDisplayed()
        await (await ECO_InspectionPage.Services).click()
        expect(await ECO_InspectionPage.Services).toBeDisplayed()
        await (ECO_InspectionPage.scooter_Inspection).click()
        expect(ECO_InspectionPage.scooter_InspectionHeading).toBeDisplayed()
        expect(ECO_InspectionPage.ECOHeading).toHaveTextContaining("Get A Used Scooter Inspection With ECO")
        console.log(await (await ECO_InspectionPage.scooter_InspectionHeading).getText())
        console.log("Scooter Inspection page show")
    });
});