const base = require('../../BaseClass/base');
const Base = require('../../BaseClass/base');
const usedCarPage = require('../../Pages/iOS/usedCarPage');
const UsedCarPage = require("../../Pages/iOS/usedCarPage")
describe('Used Car', async () => {
  beforeEach(async  ()=>{
      
    await driver.closeApp()
    await driver.launchApp()
  });  
   it('TC01 Verify car option is the display with used Condition to the buyer', async () => {
     //await Base.iosLoginAsBuyer()
     //await base.skipStartup()
     console.log("Create Requirement")
     await (await UsedCarPage.createReq).waitForDisplayed()
     expect (await UsedCarPage.createReq).toBeDisabled()
     await (await UsedCarPage.createReq).click()
     console.log("Clicked On Create Requirement")
     console.log("Select Heading Displayed As:"+await(await UsedCarPage.headingSelectPage).getText())
     expect(await UsedCarPage.carimg).toBeDisplayed()
     console.log('Car option displayed')
     expect(await UsedCarPage.scooter).toBeDisplayed()
     console.log('scooter option displayed')
     expect(UsedCarPage.newButton).toBeDisplayed()
     console.log('New option displayed under condition')
     expect(await UsedCarPage.usedButton).toBeDisplayed()
     console.log('Used redio button displayed')
     expect(await UsedCarPage.location).toBeDisplayed()
     console.log('Location input box displayed')
     expect(await UsedCarPage.currentLocation).toBeDisplayed()
     console.log('Detect Current Location option displayed')
     expect(await UsedCarPage.nextButton).toBeDisplayed()
     console.log('Next button displayed')
   });
   it('TC_02 Verify user able to select location using location option', async () => {
    //await Base.skipStartup()
    console.log("Getting on Create requirement Page")
    await (await UsedCarPage.createReq).waitForDisplayed()
    expect (await UsedCarPage.createReq).toBeDisabled()
    console.log("Create Requirtement is displayed")
    await (await UsedCarPage.createReq).click()
    console.log("Clicked On Create Requirement")
    expect (await UsedCarPage.headingSelectPage).toBeDisabled()
    console.log("Select Heading Displayed As:"+await(await UsedCarPage.headingSelectPage).getText())
    expect(await UsedCarPage.currentLocation).toBeDisplayed()
    console.log('Current Location displayed')
    expect(await UsedCarPage.currentLocation).toBeClickable()
    console.log('Current Location is Clickable')
  });
   it('TC_03 Verify error message without entering location', async () => {
    //await Base.skipStartup()
    await (await UsedCarPage.createReq).waitForDisplayed()
    expect (await UsedCarPage.createReq).toBeDisabled()
    console.log("Create Requirement is Displayed")
    await (await UsedCarPage.createReq).click()
    console.log("Clicked On Create Requirement")
    expect (await UsedCarPage.headingSelectPage).toBeDisabled()
    console.log("Select Heading Displayed As:"+await(await UsedCarPage.headingSelectPage).getText())
    expect(await UsedCarPage.currentLocation).toBeDisplayed()
    console.log('Current Location displayed')
    expect(await UsedCarPage.currentLocation).toBeClickable()
    console.log('Current Location is Clickable')
    await (await UsedCarPage.newButton).click()
    expect(UsedCarPage.errorMsg).toBeDisplayed()
    console.log('Error message Displayed')
   });
   it('TC_04 Verify user able to select Car model from Entering your vehicle details as per requirement', async () => {
    //await Base.skipStartup()
    await (await UsedCarPage.createReq).waitForDisplayed()
    expect (await UsedCarPage.createReq).toBeDisabled()
    console.log("Create Requirement is Displayed")
    await (await UsedCarPage.createReq).click()
    console.log("Clicked On Create Requirement")
    expect (await UsedCarPage.headingSelectPage).toBeDisabled()
    console.log("Select Heading Displayed As:"+await(await UsedCarPage.headingSelectPage).getText())
    await(await UsedCarPage.nextButton).click()
    console.log("CLicked On Next Button")
    await (await UsedCarPage.selectCarHeading).waitForEnabled({timeout: 10000 })
    expect (await UsedCarPage.selectCarHeading).toBeDisabled()
    console.log("Select Heading Displayed As:"+await(await UsedCarPage.selectCarHeading).getText())
    await (await UsedCarPage.droomSugg).waitForDisplayed({timeout: 30000 })
    expect(await UsedCarPage.vehicleDetails).toBeDisplayed()
    console.log("Enter DFetails Lable Displayed As:"+await(await UsedCarPage.vehicleDetails).getText())
    expect(await UsedCarPage.searchTextField).toBeDisplayed()
    console.log("Text field to eneter required Vehicle Details id displayed")
    await (await UsedCarPage.searchTextField).setValue("Maruti Suzuki Swift")
    console.log("Setting the value to be search")
    expect(await UsedCarPage.selectSearchResult).toBeDisplayed()
    console.log("Select Search Result Displayed As:"+await(await UsedCarPage.selectSearchResult).getText())
    expect(await UsedCarPage.doneBtn).toBeDisplayed()
    console.log("Done Button displayed on Select Search Result")
    expect(await UsedCarPage.cancelBtn).toBeDisplayed()
    console.log("Cancel Button displayed on Select Search Result")
    await(await UsedCarPage.doneBtn).click()
    console.log("CLicked on Done Button")
    expect(await UsedCarPage.addmoreVerhicle).toBeDisplayed()
    console.log("user able to select Car model from Entering your vehicle details as per requirement")
});

   it('TC_05 Verify user able to select car model through select from the dropdown as per requirement', async () => {
    //await Base.skipStartup()
    await (await UsedCarPage.createReq).waitForDisplayed()
    expect (await UsedCarPage.createReq).toBeDisabled()
    console.log("Create Requirement is Displayed")
    await (await UsedCarPage.createReq).click()
    console.log("Clicked On Create Requirement")
    expect (await UsedCarPage.createReq).toBeDisabled()
    console.log("Select Heading Displayed As:"+await(await UsedCarPage.headingSelectPage).getText())
    await (await UsedCarPage.nextButton).click()
    console.log("CLicked On Next Button")
    await (await UsedCarPage.selectCarHeading).waitForEnabled({timeout: 10000 })
    expect (await UsedCarPage.selectCarHeading).toBeDisabled()
    console.log("Select Heading Displayed As:"+await(await UsedCarPage.selectCarHeading).getText())
    await (await UsedCarPage.droomSugg).waitForEnabled({timeout: 30000 })
    expect(await UsedCarPage.vehicleDetails).toBeDisplayed()
    console.log("Enter Details Lable Displayed As:"+await(await UsedCarPage.vehicleDetails).getText()) 
    //await(await usedCarPage.selectVehicle).click()
    //console.log("Clicked on Select Vehicle")
   //Select Make, Model, Year and trim has no locatotrs there..partially DOne
   });

   it('TC_06 Verify user able to select car model through Let Droom Suggest for you as per requirement', async () => {
    //await base.skipStartup()
    await (await UsedCarPage.createReq).waitForDisplayed()
    await (await UsedCarPage.createReq).click()
    console.log("Clicked On Create Requirement")
    expect (await UsedCarPage.createReq).toBeDisabled()
    console.log("Select Heading Displayed As:"+await(await UsedCarPage.headingSelectPage).getText())
    await (await UsedCarPage.newButton).click()
    console.log("Clicked On Next Button")
    await (await UsedCarPage.selectCarHeading).waitForEnabled({timeout: 10000 })
    expect (await UsedCarPage.selectCarHeading).toBeDisabled()
    console.log("Select Heading Displayed As:"+await(await UsedCarPage.selectCarHeading).getText())
    await (await UsedCarPage.droomSugg).waitForEnabled({timeout: 30000 })
    expect (await UsedCarPage.droomSugg).toBeDisabled()
    console.log("Select Heading Displayed As:"+await(await UsedCarPage.droomSugg).getText())
    expect(await usedCarPage.bodyType).toBeDisplayed()
    console.log("Get Personalised Suggestion page get displayed for suggestion")
   });
   
it('TC_07 Verify user able to select used car as per the budget', async () => {
  //await base.skipStartup()
  await (await UsedCarPage.createReq).waitForDisplayed()
  expect (await UsedCarPage.createReq).toBeDisabled()
  console.log("Create Requirement is Displayed")
  await (await UsedCarPage.createReq).click()
  console.log("Clicked On Create Requirement")
  await(await UsedCarPage.nextButton).click()
  console.log("Clicked On Next Button")
  expect (await UsedCarPage.selectCarHeading).toBeDisabled()
  console.log("Select Heading Displayed As:"+await(await UsedCarPage.selectCarHeading).getText())
  await (await UsedCarPage.droomSugg).waitForEnabled({timeout: 30000 })
  expect (await UsedCarPage.droomSugg).toBeDisabled()
  console.log("Select Heading Displayed As:"+await(await UsedCarPage.droomSugg).getText())
  expect(await usedCarPage.priceRange).toBeDisplayed()
  console.log("Price Range displayed on page")
   });
  
  it('TC08 Verify user able to select used car as per the Fuel type', async () => {
  //await base.skipStartup()
  await (await UsedCarPage.createReq).waitForDisplayed()
  expect (await UsedCarPage.createReq).toBeDisabled()
  console.log("Create Requirement is Displayed")
  await (await UsedCarPage.createReq).click()
  console.log("Clicked On Create Requirement")
  await(await UsedCarPage.nextButton).click()
  console.log("Clicked On Next Button")
  expect (await UsedCarPage.selectCarHeading).toBeDisabled()
  console.log("Select Heading Displayed As:"+await(await UsedCarPage.selectCarHeading).getText())
    await (await UsedCarPage.droomSugg).waitForEnabled({timeout: 30000 })
    expect (await UsedCarPage.droomSugg).toBeDisabled()
    console.log("Select Heading Displayed As:"+await(await UsedCarPage.droomSugg).getText())
    await (await UsedCarPage.droomSugg).click()
    console.log("Clicked on Let's Droom Suggest for You ")
    expect(await usedCarPage.suv).toBeDisplayed()
    console.log("Body Types displayed for suggestion")
    await(await usedCarPage.suv).click()
    console.log("Clicked on SUV Body type")
    await(await usedCarPage.nextButton).click()
    console.log("Clicked on Next Button")
    expect(await usedCarPage.lastStepHeading).toBeDisplayed()
    console.log("Last step page Heading Displayed As:"+await(await UsedCarPage.lastStepHeading).getText())
    expect(await usedCarPage.urCriteria).toBeDisplayed()
    console.log("Select Vechile Displayed With:"+await(await UsedCarPage.urCriteria).getText())
    await(await usedCarPage.fortEcoSport).click()
    console.log("Selected the Fort Ecosport Option")
    await(await usedCarPage.nextButton).click()
    console.log("Clicked on Next Button")
    expect(await usedCarPage.fuleTypes).toBeDisplayed()
    console.log("Fuel Types displayed") 
    expect(await usedCarPage.petrol).toBeDisplayed()
    console.log("Petrol Fuel Type displayed")
  });
  
it('TC_09 Verify user able to select used car as per the KMS Driven Range',async () =>{
  //await base.skipStartup()
  await (await UsedCarPage.createReq).waitForDisplayed()
  expect (await UsedCarPage.createReq).toBeDisabled()
  console.log("Create Requirement is Displayed")
  await (await UsedCarPage.createReq).click()
  console.log("Clicked On Create Requirement")
  await(await UsedCarPage.nextButton).click()
  console.log("Clicked On Next Button")
  expect (await UsedCarPage.selectCarHeading).toBeDisabled()
  console.log("Select Heading Displayed As:"+await(await UsedCarPage.selectCarHeading).getText())
    await (await UsedCarPage.droomSugg).waitForEnabled({timeout: 30000 })
    expect (await UsedCarPage.droomSugg).toBeDisabled()
    console.log("Select Heading Displayed As:"+await(await UsedCarPage.droomSugg).getText())
    await (await UsedCarPage.droomSugg).click()
    console.log("Clicked on Let's Droom Suggest for You ")
    expect(await usedCarPage.suv).toBeDisplayed()
    console.log("Body Types displayed for suggestion")
    await(await usedCarPage.suv).click()
    console.log("Clicked on SUV Body type")
    await(await usedCarPage.nextButton).click()
    console.log("Clicked on Next Button")
    expect(await usedCarPage.lastStepHeading).toBeDisplayed()
    console.log("Last step page Heading Displayed As:"+await(await UsedCarPage.lastStepHeading).getText())
    expect(await usedCarPage.urCriteria).toBeDisplayed()
    console.log("Select Vechile Displayed With:"+await(await UsedCarPage.urCriteria).getText())
    await(await usedCarPage.fortEcoSport).click()
    console.log("Selected the Fort Ecosport Option")
    await(await usedCarPage.nextButton).click()
    console.log("Clicked on Next Button")
    expect(await usedCarPage.fuleTypes).toBeDisplayed()
    console.log("Now Share Your Dream Vehicle Basic Details Page displayed")
    expect(await usedCarPage.kmsSlider).toBeDisplayed()
    console.log("KM Driven Range displayed")
    await(await usedCarPage.nextButton).click()
    console.log("Clicked on Next Button")
    await(await usedCarPage.nextButton).click()
    console.log("Clicked on Next Button")
    expect(await usedCarPage.continueWithMblNo).toBeDisplayed()
    console.log("Continue with mobile Number on last page is displayed")
    expect(await usedCarPage.continue).toBeDisplayed()
    console.log("Continue Button displayed towards OTP page")
});

it('TC_10 Verify user able to select use car as per the Exterior Color', async () => {
  //await base.skipStartup()
  await (await UsedCarPage.createReq).waitForDisplayed()
  expect (await UsedCarPage.createReq).toBeDisabled()
  console.log("Create Requirement is Displayed")
  await (await UsedCarPage.createReq).click()
  console.log("Clicked On Create Requirement")
  await(await UsedCarPage.nextButton).click()
  console.log("Clicked On Next Button")
  expect (await UsedCarPage.selectCarHeading).toBeDisabled()
  console.log("Select Heading Displayed As:"+await(await UsedCarPage.selectCarHeading).getText())
  await (await UsedCarPage.droomSugg).waitForEnabled({timeout: 30000 })
  expect (await UsedCarPage.droomSugg).toBeDisabled()
  console.log("Select Heading Displayed As:"+await(await UsedCarPage.droomSugg).getText())
  await (await UsedCarPage.droomSugg).click()
    console.log("Clicked on Let's Droom Suggest for You ")
  expect(await usedCarPage.suv).toBeDisplayed()
  console.log("Body Types displayed for suggestion")
  await(await usedCarPage.suv).click()
  console.log("Clicked on SUV Body type")
  await(await usedCarPage.nextButton).click()
  console.log("Clicked on Next Button")
  expect(await usedCarPage.lastStepHeading).toBeDisplayed()
  console.log("Last step page Heading Displayed As:"+await(await UsedCarPage.lastStepHeading).getText())
  expect(await usedCarPage.urCriteria).toBeDisplayed()
  console.log("Select Vechile Displayed With:"+await(await UsedCarPage.urCriteria).getText())
  await(await usedCarPage.fortEcoSport).click()
  console.log("Selected the Fort Ecosport Option")
  await(await usedCarPage.nextButton).click()
  console.log("Clicked on Next Button")
  expect(await usedCarPage.redColor).toBeDisplayed()
  expect(await usedCarPage.balckColor).toBeDisplayed()
  console.log("Red ,Black and some colours are displayed for choice")
  await(await usedCarPage.balckColor).click()
  console.log("User clicked on Black Color")
  await(await usedCarPage.nextButton).click()
  console.log("Clicked on Next Button")
  expect(await usedCarPage.laststepExploreVehicle).toBeDisplayed()
  console.log("Page Displayed after click on Next Button with Heading:"+await(await UsedCarPage.laststepExploreVehicle).getText())
  await(await usedCarPage.nextButton).click()
  console.log("Clicked on Next Button")
  expect(await usedCarPage.oneLastStepBeforeMatch).toBeDisplayed()
  console.log("Page Displayed after click on Next Button with Heading:"+await(await UsedCarPage.oneLastStepBeforeMatch).getText())
  await(await usedCarPage.nextButton).click()
  console.log("Clicked on Next Button")
  expect(await usedCarPage.submitAndView).toBeDisplayed()
  console.log("Submit and View Button is Displayed")
  await(await usedCarPage.submitAndView).click()
  console.log("CLicked on Submit and View all Mathche")
  expect(await usedCarPage.continueWithMblNo).toBeDisplayed()
  console.log("User Successfully towards get OTP on Mobile Number for Create Requirement")
});
it('TC_11 Verify user able to select use car as per the Transmission Type', async () => {
  //await base.skipStartup()
  await (await UsedCarPage.createReq).waitForDisplayed()
  expect (await UsedCarPage.createReq).toBeDisabled()
  console.log("Create Requirement is Displayed")
  await (await UsedCarPage.createReq).click()
  console.log("Clicked On Create Requirement")
  await(await UsedCarPage.nextButton).click()
  console.log("Clicked On Next Button")
  expect (await UsedCarPage.selectCarHeading).toBeDisabled()
  console.log("Select Heading Displayed As:"+await(await UsedCarPage.selectCarHeading).getText())
  await (await UsedCarPage.droomSugg).waitForEnabled({timeout: 30000 })
  expect (await UsedCarPage.droomSugg).toBeDisabled()
  console.log("Select Heading Displayed As:"+await(await UsedCarPage.droomSugg).getText())
  await (await UsedCarPage.droomSugg).click()
  console.log("Clicked on Let's Droom Suggest for You ")
  expect(await usedCarPage.suv).toBeDisplayed()
  console.log("Body Types displayed for suggestion")
  await(await usedCarPage.suv).click()
  console.log("Clicked on SUV Body type")
  await(await usedCarPage.nextButton).click()
  console.log("Clicked on Next Button")
  expect(await usedCarPage.lastStepHeading).toBeDisplayed()
  console.log("Last step page Heading Displayed As:"+await(await UsedCarPage.lastStepHeading).getText())
  expect(await usedCarPage.urCriteria).toBeDisplayed()
  console.log("Select Vechile Displayed With:"+await(await UsedCarPage.urCriteria).getText())
  await(await usedCarPage.fortEcoSport).click()
  console.log("Selected the Fort Ecosport Option")
  await(await usedCarPage.nextButton).click()
  console.log("Clicked on Next Button")
  expect(await usedCarPage.transmissionType).toBeDisplayed()
  console.log("Manual and Automatic Transmission Types are displayed for choice")
  await(await usedCarPage.manualTransmission).click()
  console.log("User clicked on Manual Transmission Type")
  await(await usedCarPage.nextButton).click()
  console.log("Clicked on Next Button")
  expect(await usedCarPage.laststepExploreVehicle).toBeDisplayed()
  console.log("Page Displayed after click on Next Button with Heading:"+await(await UsedCarPage.laststepExploreVehicle).getText())
  await(await usedCarPage.nextButton).click()
  console.log("Clicked on Next Button")
  expect(await usedCarPage.oneLastStepBeforeMatch).toBeDisplayed()
  console.log("Page Displayed after click on Next Button with Heading:"+await(await UsedCarPage.oneLastStepBeforeMatch).getText())
  await(await usedCarPage.nextButton).click()
  console.log("Clicked on Next Button")
  expect(await usedCarPage.submitAndView).toBeDisplayed()
  console.log("Submit and View Button is Displayed")
  await(await usedCarPage.continue).waitForDisplayed()
  console.log("Clicked on Submit and View all Mathche")
  expect(await usedCarPage.continue).toBeDisplayed()
  console.log("User Successfully towards get OTP on Mobile Number for Create Requirement")
 });
 
 it('TC_12 Verify user able to select use car as per the Do you also need option', async () => {
  //await base.skipStartup()
  await (await UsedCarPage.createReq).waitForDisplayed()
  expect (await UsedCarPage.createReq).toBeDisabled()
  console.log("Create Requirement is Displayed")
  await (await UsedCarPage.createReq).click()
  console.log("Clicked On Create Requirement")
  await(await UsedCarPage.nextButton).click()
  console.log("Clicked On Next Button")
  expect (await UsedCarPage.selectCarHeading).toBeDisabled()
  console.log("Select Heading Displayed As:"+await(await UsedCarPage.selectCarHeading).getText())
  await (await UsedCarPage.droomSugg).waitForEnabled({timeout: 30000 })
  expect (await UsedCarPage.droomSugg).toBeDisabled()
  console.log("Select Heading Displayed As:"+await(await UsedCarPage.droomSugg).getText())
  await (await UsedCarPage.droomSugg).click()
    console.log("Clicked on Let's Droom suggest for You ")
  expect(await usedCarPage.suv).toBeDisplayed()
  console.log("Body Types displayed for suggestion")
  await(await usedCarPage.suv).click()
  console.log("Clicked on SUV Body type")
  await(await usedCarPage.nextButton).click()
  console.log("Clicked on Next Button")
  expect(await usedCarPage.lastStepHeading).toBeDisplayed()
  console.log("Last step page Heading Displayed As:"+await(await UsedCarPage.lastStepHeading).getText())
  expect(await usedCarPage.urCriteria).toBeDisplayed()
  console.log("Select Vechile Displayed With:"+await(await UsedCarPage.urCriteria).getText())
  await(await usedCarPage.fortEcoSport).click()
  console.log("Selected the Fort Ecosport Option")
  await(await usedCarPage.nextButton).click()
  console.log("Clicked on Next Button")
  await(await usedCarPage.nextButton).click()
  console.log("Clicked on Next Button")
  await (await usedCarPage.lastStep).waitForExist({ timeout: 5000 })
  expect (await usedCarPage.lastStep).toBeDisplayed()
  console.log("Last step page Displayed With:"+await(await UsedCarPage.lastStep).getText())
  expect (await usedCarPage.insurance).toBeDisplayed()
  console.log("Do you also need Insurance Option is displayed")
  expect (await usedCarPage.loan).toBeDisplayed()
  console.log("Do you also need Loan Option is displayed")
  expect (await usedCarPage.RCTransfer).toBeDisplayed()
  console.log("Do you also need RC Transfer Option is displayed")
  expect (await usedCarPage.roadSideAssistance).toBeDisplayed()
  console.log("Do you also need InsurRoad side Assistance Option is displayed")
  await (await usedCarPage.insurance).click()
  console.log("Selected the Insurance Option")
  await(await usedCarPage.nextButton).click()
  console.log("Clicked on Next Button")
  expect (await usedCarPage.oneLastStepBeforeMatch).toBeDisplayed()
  console.log("user able to select use car as per the Do you also need option")
});
   it('TC_13 Verify user is able to select use car as per the How Quickly Do You Want to Buy? option', async () => {
   // await base.skipStartup()
    await (await UsedCarPage.createReq).click()
    console.log("Clicked On Create Requirement")
    expect (await UsedCarPage.createReq).toBeDisabled()
    console.log("Select Heading Displayed As:"+await(await UsedCarPage.headingSelectPage).getText())
    await(await UsedCarPage.nextButton).click()
  console.log("Clicked On Next Button")
    await (await UsedCarPage.selectCarHeading).waitForEnabled({timeout: 10000 })
    expect (await UsedCarPage.selectCarHeading).toBeDisabled()
    console.log("Select Heading Displayed As:"+await(await UsedCarPage.selectCarHeading).getText())
    await (await UsedCarPage.droomSugg).waitForEnabled({timeout: 30000 })
    expect (await UsedCarPage.droomSugg).toBeDisabled()
    console.log("Select Heading Displayed As:"+await(await UsedCarPage.droomSugg).getText())
    await (await UsedCarPage.droomSugg).click()
    console.log("Clicked on Let's Droom Suggest for You ")
    expect(await usedCarPage.suv).toBeDisplayed()
    console.log("Body Types displayed for suggestion")
    await(await usedCarPage.suv).click()
    console.log("Clicked on SUV Body type")
    await(await usedCarPage.nextButton).click()
    console.log("Clicked on Next Button")
    expect(await usedCarPage.lastStepHeading).toBeDisplayed()
    console.log("Last step page Heading Displayed As:"+await(await UsedCarPage.lastStepHeading).getText())
    expect(await usedCarPage.urCriteria).toBeDisplayed()
    console.log("Select Vechile Displayed With:"+await(await UsedCarPage.urCriteria).getText())
    await(await usedCarPage.fortEcoSport).click()
    console.log("Selected the Fort Ecosport Option")
    await(await usedCarPage.nextButton).click()
    console.log("Clicked on Next Button")
    await(await usedCarPage.nextButton).click()
    console.log("Clicked on Next Button")
    await (await usedCarPage.lastStep).waitForExist({ timeout: 5000 })
    expect (await usedCarPage.lastStep).toBeDisplayed()
    console.log("Last step page Displayed With:"+await(await UsedCarPage.lastStep).getText())
    expect (await usedCarPage.insurance).toBeDisplayed()
    console.log("Do you also need Insurance Option is displayed")
    //expect(await usedCarPage.howQuicklyUwantBuy).toBeDisplayed()
    //console.log("How Quickly Displayed With:"+await(await UsedCarPage.howQuicklyUwantBuy).getText())
    expect (await usedCarPage.withinFourDay).toBeDisplayed()
    console.log("Buy within four Days option displayed")
    await (await usedCarPage.withinFourDay).click()
    console.log("Clicked on within Four Days option to Buy ")
    await(await usedCarPage.nextButton).click()
    console.log("Clicked on Next Button")
    expect(await usedCarPage.oneLastStepBeforeMatch).toBeDisplayed()
    console.log("user is able to select use car as per the How Quickly Do You Want to Buy? option")  
  });
  it('TC_14 Verify user is able to select used car as per the Do You Wish to Exchange Your Vehicle option', async () => {
   //await base.skipStartup()
    await (await UsedCarPage.createReq).click()
    console.log("Clicked On Create Requirement")
    expect (await UsedCarPage.headingSelectPage).toBeDisabled()
    console.log("Select Heading Displayed As:"+await(await UsedCarPage.headingSelectPage).getText())
    await(await usedCarPage.nextButton).click()
    console.log("Clicked on Next Button")
    await (await UsedCarPage.selectCarHeading).waitForEnabled({timeout: 10000 })
    expect (await UsedCarPage.selectCarHeading).toBeDisabled()
    console.log("Select Heading Displayed As:"+await(await UsedCarPage.selectCarHeading).getText())
    await (await UsedCarPage.droomSugg).waitForEnabled({timeout: 30000 })
    expect (await UsedCarPage.droomSugg).toBeDisabled()
    console.log("Select Heading Displayed As:"+await(await UsedCarPage.droomSugg).getText())
    await (await UsedCarPage.droomSugg).click()
    console.log("Clicked on Let's Droom Suggest for You ")
    expect(await usedCarPage.suv).toBeDisplayed()
    console.log("Body Types displayed for suggestion")
    await(await usedCarPage.suv).click()
    console.log("Clicked on SUV Body type")
    await(await usedCarPage.nextButton).click()
    console.log("Clicked on Next Button")
    expect(await usedCarPage.lastStepHeading).toBeDisplayed()
    console.log("Last step page Heading Displayed As:"+await(await UsedCarPage.lastStepHeading).getText())
    expect(await usedCarPage.urCriteria).toBeDisplayed()
    console.log("Select Vechile Displayed With:"+await(await UsedCarPage.urCriteria).getText())
    await(await usedCarPage.fortEcoSport).click()
    console.log("Selected the Fort Ecosport Option")
    await(await usedCarPage.nextButton).click()
    console.log("Clicked on Next Button")
    await(await usedCarPage.nextButton).click()
    console.log("Clicked on Next Button")
    await (await usedCarPage.lastStep).waitForExist({ timeout: 5000 })
    expect (await usedCarPage.lastStep).toBeDisplayed()
    console.log("Last step page Displayed With:"+await(await UsedCarPage.lastStep).getText())
    expect (await usedCarPage.insurance).toBeDisplayed()
    console.log("Do you also need Insurance Option is displayed")
    expect (await usedCarPage.doUwishExchange).toBeDisplayed()
    console.log("Do You Wish to Excahnge Your Vehicle Displayedption displayed")
    console.log("With Option No Used Going to click on Next Button")
    await(await usedCarPage.nextButton).click()
    console.log("Clicked on Next Button")
    expect(await usedCarPage.oneLastStepBeforeMatch).toBeDisplayed()
    console.log("User Successfully went on next page")
    console.log("Verified User is able to select used car as per the Do You Wish to Exchange Your Vehicle option") 
  });

  it('TC_15 Validation for match count while requirement creation and in requirement page', async () => {
    //await base.iosLoginAsBuyer()
    await (await UsedCarPage.createReq).click()
    console.log("Clicked On Create Requirement")
    expect (await UsedCarPage.createReq).toBeDisabled()
    console.log("Select Heading Displayed As:"+await(await UsedCarPage.headingSelectPage).getText())
    await(await usedCarPage.nextButton).click()
    console.log("Clicked on Next Button")
    await (await UsedCarPage.selectCarHeading).waitForEnabled({timeout: 10000 })
    expect (await UsedCarPage.selectCarHeading).toBeDisabled()
    console.log("Select Heading Displayed As:"+await(await UsedCarPage.selectCarHeading).getText())
    await (await UsedCarPage.droomSugg).waitForEnabled({timeout: 30000 })
    expect (await UsedCarPage.droomSugg).toBeDisabled()
    console.log("Select Heading Displayed As:"+await(await UsedCarPage.droomSugg).getText())
    await (await UsedCarPage.droomSugg).click()
    console.log("Clicked on Let's Droom Suggest for You ")
    expect(await usedCarPage.suv).toBeDisplayed()
    console.log("Body Types displayed for suggestion")
    await(await usedCarPage.suv).click()
    console.log("Clicked on SUV Body type")
    await(await usedCarPage.nextButton).click()
    console.log("Clicked on Next Button")
    expect(await usedCarPage.lastStepHeading).toBeDisplayed()
    console.log("Last step page Heading Displayed As:"+await(await UsedCarPage.lastStepHeading).getText())
    expect(await usedCarPage.urCriteria).toBeDisplayed()
    console.log("Select Vechile Displayed With:"+await(await UsedCarPage.urCriteria).getText())
    await(await usedCarPage.fortEcoSport).click()
    console.log("Selected the Fort Ecosport Option")
    await(await usedCarPage.nextButton).click()
    console.log("Clicked on Next Button")
    await(await usedCarPage.nextButton).click()
    console.log("Clicked on Next Button")
    await (await usedCarPage.lastStep).waitForExist({ timeout: 5000 })
    expect (await usedCarPage.lastStep).toBeDisplayed()
    console.log("Last step page Displayed With:"+await(await UsedCarPage.lastStep).getText())
    await(await usedCarPage.nextButton).click()
    console.log("Clicked on Next Button")
    expect(await usedCarPage.oneLastStepBeforeMatch).toBeDisplayed()
  });
  
});