const { default: doubleClick } = require("webdriverio/build/commands/element/doubleClick");
const base = require("../../BaseClass/base");
const vehicleInsurancePage = require("../../Pages/iOS/vehicleInsurancePage");

describe("Vehicle Insurance", () => {
    beforeEach(async () => {
        await driver.closeApp()
        await driver.launchApp()
    });
 it("TC_01 Verify The Functionality Of Get Insurance", async () => {
        //await base.skipStartup()
        //await base.iosLoginAsBuyer()
        await vehicleInsurancePage.traverseToVehicleInsurance()
        expect(await vehicleInsurancePage.searchingFor).toBeDisplayed()
        console.log("You are now Vehicle Insurance Page")
        await (await vehicleInsurancePage.loanInsurance).click()
        console.log("clicked on loan And Insurance")
        await (await vehicleInsurancePage.insurance).click()
        console.log("clicked on Insurance")
        await (await vehicleInsurancePage.proceed).click()
        console.log("clicked on proceed")
        expect(await vehicleInsurancePage.personalInformation).toBeDisplayed()
        console.log("User Successfully proceed to Personal Inforamtion Page")
        expect(await vehicleInsurancePage.fullname_field).toBeDisplayed()
        console.log("fullname  fiels id displayed")
        console.log(await (await vehicleInsurancePage.fullname_field).getText())
        expect(await vehicleInsurancePage.email_id_field).toBeDisplayed()
        console.log("Email Id field is displayed")
        console.log(await (await vehicleInsurancePage.email_id_field).getText())
        expect(await vehicleInsurancePage.contact_number_field).toBeDisplayed()
        console.log("contact number Displayed")
        console.log(await (await vehicleInsurancePage.contact_number_field).getText())
        expect(await vehicleInsurancePage.location_field).toBeDisplayed()
        console.log("Loaction displayed")
        console.log(await (await vehicleInsurancePage.location_field).getText())
        expect(await vehicleInsurancePage.btn_next_step1).toBeDisplayed()
        console.log("Proceed to step 2 displayed")
    });
  it("TC_02 Verify Select vehicle Condition Used functionality", async () => {
        //await base.androidLoginAsBuyer()
        await vehicleInsurancePage.traverseToVehicleInsurance()
        await (await vehicleInsurancePage.loanInsurance).click()
        console.log("clicked on loan And Insurance")
        await (await vehicleInsurancePage.insurance).click()
        console.log("clicked on Insurance")
        await (await vehicleInsurancePage.proceed).click()
        console.log("clicked on proceed")
        expect(await vehicleInsurancePage.fullname_field).toBeDisplayed()
        console.log("fullname:")
        console.log(await (await vehicleInsurancePage.fullname_field).getText())
        expect(await vehicleInsurancePage.email_id_field).toBeDisplayed()
        console.log("Email Id:")
        console.log(await (await vehicleInsurancePage.email_id_field).getText())
        expect(await vehicleInsurancePage.contact_number_field).toBeDisplayed()
        console.log("contact number:")
        console.log(await (await vehicleInsurancePage.contact_number_field).getText())
        expect(await vehicleInsurancePage.location_field).toBeDisplayed()
        console.log("Location:")
        console.log(await (await vehicleInsurancePage.location_field).getText())
        await browser.pause(1000)
        await (await vehicleInsurancePage.btn_next_step1).click()
        await (await vehicleInsurancePage.close_OTP).click()
        await (await vehicleInsurancePage.radio_yes).click()
        expect(await vehicleInsurancePage.radio_yes).toBeDisplayed()
        console.log("Used Button Displayed")
    });
   it("TC_03 Verify the process to Apply for Vehicle Insurance in 3 Easy Steps", async () => {
    await vehicleInsurancePage.traverseToVehicleInsurance()
        await (await vehicleInsurancePage.services).click()
        console.log("Clicked on All services")
        await (await vehicleInsurancePage.loanInsurance).click()
        console.log("clicked on loan And Insurance")
        await (await vehicleInsurancePage.insurance).click()
        console.log("clicked on Insurance")
        await (await vehicleInsurancePage.proceed).click()
        console.log("clicked on proceed")
        expect(await vehicleInsurancePage.fullname_field).toBeDisplayed()
        expect(await vehicleInsurancePage.email_id_field).toBeDisplayed()
        expect(await vehicleInsurancePage.contact_number_field).toBeDisplayed()
        expect(await vehicleInsurancePage.location_field).toBeDisplayed()
        await (await vehicleInsurancePage.btn_next_step1).click()
        await (await vehicleInsurancePage.close_OTP).click()
        await (await vehicleInsurancePage.radio_yes).click()
        expect(await vehicleInsurancePage.radio_yes).toBeDisplayed()
        expect(await vehicleInsurancePage.personalInformation).toBeDisplayed()
        console.log("Personal Information tab displayed")
        expect(await vehicleInsurancePage.vehicleInformation).toBeDisplayed()
        console.log("Vehicle Information tab displayed")
        expect(await vehicleInsurancePage.insuranceInformation).toBeDisplayed()
        console.log("Vehicle Information tab displayed")
    });
    
    it("TC_04 Verify Select vehicle Condition New functionality", async () => {
       // await base.skipStartup()
        //await base.iosLoginAsBuyer()
        await vehicleInsurancePage.traverseToVehicleInsurance()
        await (await vehicleInsurancePage.loanInsurance).click()
        console.log("clicked on loan And Insurance")
        await (await vehicleInsurancePage.insurance).click()
        console.log("clicked on Insurance")
        await (await vehicleInsurancePage.proceed).click()
        console.log("clicked on proceed")
        expect(await vehicleInsurancePage.fullname_field).toBeDisplayed()
        console.log("fullname:")
        console.log(await (await vehicleInsurancePage.fullname_field).getText())
        expect(await vehicleInsurancePage.email_id_field).toBeDisplayed()
        console.log("Email Id:")
        console.log(await (await vehicleInsurancePage.email_id_field).getText())
        expect(await vehicleInsurancePage.contact_number_field).toBeDisplayed()
        console.log("contact number:")
        console.log(await (await vehicleInsurancePage.contact_number_field).getText())
        expect(await vehicleInsurancePage.location_field).toBeDisplayed()
        console.log("Loaction:")
        console.log(await (await vehicleInsurancePage.location_field).getText())
        await (await vehicleInsurancePage.btn_next_step1).click()
        await (await vehicleInsurancePage.close_OTP).click()
        await (await vehicleInsurancePage.radio_no).click()
        expect(await vehicleInsurancePage.radio_no).toBeDisplayed()
        console.log("New Button Displayed")
    });
    
    it("TC_05 Verify Select From Dropdown functionality", async () => {
        //await base.androidLoginAsBuyer()
        await vehicleInsurancePage.traverseToVehicleInsurance()
        await (await vehicleInsurancePage.loanInsurance).click()
        console.log("clicked on loan And Insurance")
        await (await vehicleInsurancePage.insurance).click()
        console.log("clicked on Insurance")
        await (await vehicleInsurancePage.proceed).click()
        console.log("clicked on proceed")
        expect(await vehicleInsurancePage.fullname_field).toBeDisplayed()
        console.log("fullname:")
        console.log(await (await vehicleInsurancePage.fullname_field).getText())
        expect(await vehicleInsurancePage.email_id_field).toBeDisplayed()
        console.log("Email Id:")
        console.log(await (await vehicleInsurancePage.email_id_field).getText())
        expect(await vehicleInsurancePage.contact_number_field).toBeDisplayed()
        console.log("contact number:")
        console.log(await (await vehicleInsurancePage.contact_number_field).getText())
        expect(await vehicleInsurancePage.location_field).toBeDisplayed()
        console.log("Loaction:")
        console.log(await (await vehicleInsurancePage.location_field).getText())
        await (await vehicleInsurancePage.btn_next_step1).click()
        await (await vehicleInsurancePage.close_OTP).click()
        expect(await vehicleInsurancePage.radio_no).toBeDisplayed()
        console.log("New Button Displayed")
        expect(await vehicleInsurancePage.make).toBeDisplayed()
        console.log("Make displayed")
        expect(await vehicleInsurancePage.model).toBeDisplayed()
        console.log("Model Displayed")
        expect(await vehicleInsurancePage.trim).toBeDisplayed()
        console.log("Trim displayed")
        expect(await vehicleInsurancePage.year).toBeDisplayed()
        console.log("Year Displayed")
    });
it("TC_06 Verify Select Make functionality of Select From Dropdown option.", async () => {
        //await base.skipBtn()
        //await base.iosLoginAsBuyer()
        await vehicleInsurancePage.traverseToVehicleInsurance()
        await (await vehicleInsurancePage.loanInsurance).click()
        console.log("clicked on loan And Insurance")
        await (await vehicleInsurancePage.insurance).click()
        console.log("clicked on Insurance")
        await (await vehicleInsurancePage.proceed).click()
        console.log("clicked on proceed")
        expect(await vehicleInsurancePage.fullname_field).toBeDisplayed()
        console.log("fullname:")
        console.log(await (await vehicleInsurancePage.fullname_field).getText())
        expect(await vehicleInsurancePage.email_id_field).toBeDisplayed()
        console.log("Email Id:")
        console.log(await (await vehicleInsurancePage.email_id_field).getText())
        expect(await vehicleInsurancePage.contact_number_field).toBeDisplayed()
        console.log("contact number:")
        console.log(await (await vehicleInsurancePage.contact_number_field).getText())
        expect(await vehicleInsurancePage.location_field).toBeDisplayed()
        console.log("Loaction:")
        console.log(await (await vehicleInsurancePage.location_field).getText())
        await (await vehicleInsurancePage.btn_next_step1).click()
        await (await vehicleInsurancePage.close_OTP).click()
        expect(await vehicleInsurancePage.radio_no).toBeDisplayed()
        console.log("New Button Displayed")
        await browser.pause(5000)
        expect (await vehicleInsurancePage.vehicleType).toBeDisplayed()
        console.log("Select Vehicle Type Displayed")
        await (await vehicleInsurancePage.vehicleType).click()
        console.log("Clicked On Select Vehicle Type")
        expect (await vehicleInsurancePage.car).toBeDisplayed()
        console.log("Car option displayed")
        //await (await vehicleInsurancePage.car).click()
       await (await vehicleInsurancePage.done).click()
        expect(await vehicleInsurancePage.make).toBeDisplayed()
       // await (await vehicleInsurancePage.make).click()
        expect(await vehicleInsurancePage.ariel).toBeDisplayed()
        await (await vehicleInsurancePage.ariel).click()
        await (await vehicleInsurancePage.done).click()
        expect(await vehicleInsurancePage.ariel).toBeDisplayed()
        
        console.log("Make selected from Dropdown")
    });
    it("TC_07 Verify Select Model functionality of Select From Dropdown option", async () => {
        //await base.skipBtn()
        //await base.iosLoginAsBuyer()
        //console.log("buyer login successfully")
        //await (await vehicleInsurancePage.buy).click()
        //console.log("clicked on Buy")
        await vehicleInsurancePage.traverseToVehicleInsurance()
        await (await vehicleInsurancePage.loanInsurance).click()
        console.log("clicked on loan And Insurance")
        await (await vehicleInsurancePage.insurance).click()
        console.log("clicked on Insurance")
        await (await vehicleInsurancePage.proceed).click()
        console.log("clicked on proceed")
        expect(await vehicleInsurancePage.fullname_field).toBeDisplayed()
        console.log("fullname:")
        console.log(await (await vehicleInsurancePage.fullname_field).getText())
        expect(await vehicleInsurancePage.email_id_field).toBeDisplayed()
        console.log("Email Id:")
        console.log(await (await vehicleInsurancePage.email_id_field).getText())
        expect(await vehicleInsurancePage.contact_number_field).toBeDisplayed()
        console.log("contact number:")
        console.log(await (await vehicleInsurancePage.contact_number_field).getText())
        expect(await vehicleInsurancePage.location_field).toBeDisplayed()
        console.log("Loaction:")
        console.log(await (await vehicleInsurancePage.location_field).getText())
        await (await vehicleInsurancePage.btn_next_step1).click()
        await (await vehicleInsurancePage.close_OTP).click()
        expect(await vehicleInsurancePage.radio_no).toBeDisplayed()
        console.log("New Button Displayed")
        await (await vehicleInsurancePage.vehicleType).click()
        console.log("Clicked Select on Vehicle Type")
        expect (await vehicleInsurancePage.car).toBeDisplayed()
        //await (await vehicleInsurancePage.car).click()
        await (await vehicleInsurancePage.done).click()
        expect(await vehicleInsurancePage.make).toBeDisplayed()
        await (await vehicleInsurancePage.make).click()
        expect(await vehicleInsurancePage.ariel).toBeDisplayed()
        await (await vehicleInsurancePage.ariel).click()
        await (await vehicleInsurancePage.done).click()
        expect(await vehicleInsurancePage.ariel).toBeDisplayed()
        console.log("Make selected from Dropdown")
        await (await vehicleInsurancePage.model).click()
        expect(await vehicleInsurancePage.atom).toBeDisplayed()
        await (await vehicleInsurancePage.atom).click()
        await (await vehicleInsurancePage.done).click()
        expect(await vehicleInsurancePage.atom).toBeDisplayed()
        console.log("model selected from Dropdown")
    });
    
    it("TC_08 Verify Select Year functionality of Select From Dropdown option.", async () => {
        //await base.skipBtn()
        //await base.iosLoginAsBuyer()
       await vehicleInsurancePage.traverseToVehicleInsurance()
        await (await vehicleInsurancePage.loanInsurance).click()
        console.log("clicked on loan And Insurance")
        await (await vehicleInsurancePage.insurance).click()
        console.log("clicked on Insurance")
        await (await vehicleInsurancePage.proceed).click()
        console.log("clicked on proceed")
        expect(await vehicleInsurancePage.fullname_field).toBeDisplayed()
        console.log("fullname:")
        console.log(await (await vehicleInsurancePage.fullname_field).getText())
        expect(await vehicleInsurancePage.email_id_field).toBeDisplayed()
        console.log("Email Id:")
        console.log(await (await vehicleInsurancePage.email_id_field).getText())
        expect(await vehicleInsurancePage.contact_number_field).toBeDisplayed()
        console.log("contact number:")
        console.log(await (await vehicleInsurancePage.contact_number_field).getText())
        expect(await vehicleInsurancePage.location_field).toBeDisplayed()
        console.log("Loaction:")
        console.log(await (await vehicleInsurancePage.location_field).getText())
        await (await vehicleInsurancePage.btn_next_step1).click()
        await (await vehicleInsurancePage.close_OTP).click()
        expect(await vehicleInsurancePage.radio_no).toBeDisplayed()
        console.log("New Button Displayed")
        await (await vehicleInsurancePage.vehicleType).click()
        await (await vehicleInsurancePage.car).click()
        expect(await vehicleInsurancePage.make).toBeDisplayed()
        await (await vehicleInsurancePage.make).click()
        expect(await vehicleInsurancePage.ariel).toBeDisplayed()
        await (await vehicleInsurancePage.ariel).click()
        await (await vehicleInsurancePage.done).click()
        expect(await vehicleInsurancePage.ariel).toBeDisplayed()
        console.log("Make selected from Dropdown")
        await (await vehicleInsurancePage.model).click()
        expect(await vehicleInsurancePage.atom).toBeDisplayed()
        await (await vehicleInsurancePage.atom).click()
        await (await vehicleInsurancePage.done).click()
        expect(await vehicleInsurancePage.atom).toBeDisplayed()
        console.log("model selected from Dropdown")
        await (await vehicleInsurancePage.year).click()
        await (await vehicleInsurancePage.done).click()
        expect(await vehicleInsurancePage.year_08).toBeDisplayed()
        console.log("Trim selected from Dropdown")
    });
    it("TC_09 Verify Select Trim functionality of Select From Dropdown option.", async () => {
        //await base.skipBtn()
        //await base.iosLoginAsBuyer()
        await vehicleInsurancePage.traverseToVehicleInsurance()
        await (await vehicleInsurancePage.buy).click()
        console.log("clicked on Buy")
        await (await vehicleInsurancePage.loanInsurance).click()
        console.log("clicked on loan And Insurance")
        await (await vehicleInsurancePage.insurance).click()
        console.log("clicked on Insurance")
        await (await vehicleInsurancePage.proceed).click()
        console.log("clicked on proceed")
        expect(await vehicleInsurancePage.fullname_field).toBeDisplayed()
        console.log("fullname:")
        console.log(await (await vehicleInsurancePage.fullname_field).getText())
        expect(await vehicleInsurancePage.email_id_field).toBeDisplayed()
        console.log("Email Id:")
        console.log(await (await vehicleInsurancePage.email_id_field).getText())
        expect(await vehicleInsurancePage.contact_number_field).toBeDisplayed()
        console.log("contact number:")
        console.log(await (await vehicleInsurancePage.contact_number_field).getText())
        expect(await vehicleInsurancePage.location_field).toBeDisplayed()
        console.log("Loaction:")
        console.log(await (await vehicleInsurancePage.location_field).getText())
        await (await vehicleInsurancePage.btn_next_step1).click()
        await (await vehicleInsurancePage.close_OTP).click()
        expect(await vehicleInsurancePage.radio_no).toBeDisplayed()
        console.log("New Button Displayed")
        await (await vehicleInsurancePage.vehicleType).click()
        await (await vehicleInsurancePage.car).click()
        expect(await vehicleInsurancePage.make).toBeDisplayed()
        await (await vehicleInsurancePage.make).click()
        expect(await vehicleInsurancePage.ariel).toBeDisplayed()
        await (await vehicleInsurancePage.ariel).click()
        await (await vehicleInsurancePage.done).click()
        expect(await vehicleInsurancePage.ariel).toBeDisplayed()
        console.log("Make selected from Dropdown")
        await (await vehicleInsurancePage.model).click()
        expect(await vehicleInsurancePage.atom).toBeDisplayed()
        await (await vehicleInsurancePage.atom).click()
        await (await vehicleInsurancePage.done).click()
        expect(await vehicleInsurancePage.atom).toBeDisplayed()
        console.log("model selected from Dropdown")
        await (await vehicleInsurancePage.trim).click()
        await (await vehicleInsurancePage.atom3).click()
        expect(await vehicleInsurancePage.atom3).toBeDisplayed()
        console.log("Trim selected from Dropdown")
    });
    
    it("TC_10 Verify the Back Button Functionality on Personal Information page of Insurance", async () => {
        await base.androidLoginAsBuyer()
        console.log("buyer login successfully")
        await browser.pause("1000")
        await (await vehicleInsurancePage.buy).click()
        console.log("clicked on Buy")
        await (await vehicleInsurancePage.loanInsurance).click()
        console.log("clicked on loan And Insurance")
        await (await vehicleInsurancePage.insurance).click()
        console.log("clicked on Insurance")
        await (await vehicleInsurancePage.proceed).click()
        console.log("clicked on proceed")
        expect(await vehicleInsurancePage.fullname_field).toBeDisplayed()
        console.log("fullname:")
        console.log(await (await vehicleInsurancePage.fullname_field).getText())
        expect(await vehicleInsurancePage.email_id_field).toBeDisplayed()
        console.log("Email Id:")
        console.log(await (await vehicleInsurancePage.email_id_field).getText())
        expect(await vehicleInsurancePage.contact_number_field).toBeDisplayed()
        console.log("contact number:")
        console.log(await (await vehicleInsurancePage.contact_number_field).getText())
        expect(await vehicleInsurancePage.location_field).toBeDisplayed()
        await (await vehicleInsurancePage.imgViewFor_location_field).click()
        await (await vehicleInsurancePage.location).setValue("Pune")
        await (await vehicleInsurancePage.pune).click()
        await (await vehicleInsurancePage.btn_next_step1).click()
        expect(await vehicleInsurancePage.radio_no).toBeDisplayed()
        console.log("New Button Displayed")
        await (await vehicleInsurancePage.vehicleType).click()
        await (await vehicleInsurancePage.car).click()
        await base.swipeUp()
        await (await vehicleInsurancePage.btn_previous_step2).click()
        expect(await vehicleInsurancePage.fullname_field).toBeDisplayed()
        expect(await vehicleInsurancePage.email_id_field).toBeDisplayed()
        expect(await vehicleInsurancePage.contact_number_field).toBeDisplayed()
    });
    it("TC_11 Verify the Next Button Functionality on Personal Information page of Insurance", async () => {
        await base.androidLoginAsBuyer()
        console.log("buyer login successfully")
        await browser.pause("1000")
        await (await vehicleInsurancePage.buy).click()
        console.log("clicked on Buy")
        await (await vehicleInsurancePage.loanInsurance).click()
        console.log("clicked on loan And Insurance")
        await (await vehicleInsurancePage.insurance).click()
        console.log("clicked on Insurance")
        await (await vehicleInsurancePage.proceed).click()
        console.log("clicked on proceed")
        expect(await vehicleInsurancePage.fullname_field).toBeDisplayed()
        console.log("fullname:")
        console.log(await (await vehicleInsurancePage.fullname_field).getText())
        expect(await vehicleInsurancePage.email_id_field).toBeDisplayed()
        console.log("Email Id:")
        console.log(await (await vehicleInsurancePage.email_id_field).getText())
        expect(await vehicleInsurancePage.contact_number_field).toBeDisplayed()
        console.log("contact number:")
        console.log(await (await vehicleInsurancePage.contact_number_field).getText())
        expect(await vehicleInsurancePage.location_field).toBeDisplayed()
        console.log("Loaction:")
        console.log(await (await vehicleInsurancePage.location_field).getText())
        await (await vehicleInsurancePage.imgViewFor_location_field).click()
        await (await vehicleInsurancePage.location).setValue("Pune")
        await (await vehicleInsurancePage.pune).click()
        await (await vehicleInsurancePage.btn_next_step1).click()
        expect(await vehicleInsurancePage.radio_no).toBeDisplayed()
        console.log("New Button Displayed")
        await (await vehicleInsurancePage.vehicleType).click()
        await (await vehicleInsurancePage.car).click()
        await (await vehicleInsurancePage.done).click()
        await (await vehicleInsurancePage.enterVehicleRN).setValue("MH14FW1234")
        await base.swipeUp()
        expect(await vehicleInsurancePage.make).toBeDisplayed()
        await (await vehicleInsurancePage.make).click()
        await (await vehicleInsurancePage.ariel).click()
        await (await vehicleInsurancePage.done).click()
        expect(await vehicleInsurancePage.ariel).toBeDisplayed()
        console.log("Make selected from Dropdown")
        await (await vehicleInsurancePage.model).click()
        await (await vehicleInsurancePage.atom).click()
        await (await vehicleInsurancePage.done).click()
        expect(await vehicleInsurancePage.atom).toBeDisplayed()
        console.log("model selected from Dropdown")
        await (await vehicleInsurancePage.trim).click()
        await (await vehicleInsurancePage.atom3).click()
        await (await vehicleInsurancePage.done).click()
        expect(await vehicleInsurancePage.atom3).toBeDisplayed()
        console.log("Trim selected from Dropdown")
        await (await vehicleInsurancePage.year).click()
        await (await vehicleInsurancePage.year_08).click()
        await (await vehicleInsurancePage.done).click()
        expect(await vehicleInsurancePage.year_08).toBeDisplayed()
        console.log("Yaer selected from Dropdown")
        await (await vehicleInsurancePage.btn_next_step2).click()
        expect(await vehicleInsurancePage.submit).toBeDisplayed()
        console.log("Submit button Display")
    });
    it("TC_12 Verify the fields on Personal Information", async () => {
        await base.skipStartup()
        await base.iosLoginAsBuyer()
        console.log("buyer login successfully")
        await browser.pause("1000")
        await (await vehicleInsurancePage.buy).click()
        console.log("clicked on Buy")
        await (await vehicleInsurancePage.loanInsurance).click()
        console.log("clicked on loan And Insurance")
        await (await vehicleInsurancePage.insurance).click()
        console.log("clicked on Insurance")
        await (await vehicleInsurancePage.proceed).click()
        console.log("clicked on proceed")
        expect(await vehicleInsurancePage.fullname_field).toBeDisplayed()
        expect(await vehicleInsurancePage.email_id_field).toBeDisplayed()
        expect(await vehicleInsurancePage.contact_number_field).toBeDisplayed()
        expect(await vehicleInsurancePage.location_field).toBeDisplayed()
        await (await vehicleInsurancePage.imgViewFor_location_field).click()
        await (await vehicleInsurancePage.location).setValue("Pune")
        await (await vehicleInsurancePage.pune).click()
        await (await vehicleInsurancePage.btn_next_step1).click()
        expect(await vehicleInsurancePage.radio_no).toBeDisplayed()
        expect(await vehicleInsurancePage.radio_yes).toBeDisplayed()
        expect(await vehicleInsurancePage.vehicleType).toBeDisplayed()
        expect(await vehicleInsurancePage.enterVehicleRN).toBeDisplayed()
        expect(await vehicleInsurancePage.make).toBeDisplayed()
        expect(await vehicleInsurancePage.model).toBeDisplayed()
        expect(await vehicleInsurancePage.trim).toBeDisplayed()
        expect(await vehicleInsurancePage.year).toBeDisplayed()
        expect(await vehicleInsurancePage.btn_next_step2).toBeDisplayed()
        expect(await vehicleInsurancePage.btn_previous_step2).toBeDisplayed()
    });
    it("TC_13 Verify the functionality of Select a vehicle Type", async () => {
        await base.androidLoginAsBuyer()
        console.log("buyer login successfully")
        await browser.pause("1000")
        await (await vehicleInsurancePage.buy).click()
        console.log("clicked on Buy")
        await (await vehicleInsurancePage.loanInsurance).click()
        console.log("clicked on loan And Insurance")
        await (await vehicleInsurancePage.insurance).click()
        console.log("clicked on Insurance")
        await (await vehicleInsurancePage.proceed).click()
        console.log("clicked on proceed")
        expect(await vehicleInsurancePage.fullname_field).toBeDisplayed()
        expect(await vehicleInsurancePage.email_id_field).toBeDisplayed()
        expect(await vehicleInsurancePage.contact_number_field).toBeDisplayed()
        expect(await vehicleInsurancePage.location_field).toBeDisplayed()
        //await (await vehicleInsurancePage.imgViewFor_location_field).click()
        await (await vehicleInsurancePage.location).setValue("Pune")
        await (await vehicleInsurancePage.pune).click()
        await (await vehicleInsurancePage.btn_next_step1).click()
        expect(await vehicleInsurancePage.radio_no).toBeDisplayed()
        expect(await vehicleInsurancePage.radio_yes).toBeDisplayed()
        expect(await vehicleInsurancePage.vehicleType).toBeDisplayed()
        await (await vehicleInsurancePage.vehicleType).click()
        await (await vehicleInsurancePage.car).click()
        expect(await vehicleInsurancePage.car).toBeDisplayed()

    });
    
});